#pragma once
class ArkTurret : CGameObjectExtensionHelper<ArkTurret,IGameObjectExtension,64>, IArkRepairableListener, IArkPlayerInteractionListener, IArkEtherDuplicateListener, IArkGlooEffectObserver
{
public:


  ArkTurretFsm m_fsm;
  ArkTurretAnimFsm::Fsm m_animFsm;
  ArkTurretDamageFsm::Fsm m_damageFsm;
  ArkTurretSignalReceiver m_signalReceiver;
  ArkTurretDialogSpeaker m_dialogSpeaker;
  ArkTurretWeapon m_turretWeapon;
  ArkGenericAttentionObject<ArkTurret> m_attentionObject;
  ArkTurretAttentiveSubject m_attentiveSubject;
  ArkRobotLight m_light;
  ArkCharacterEffectsManager m_characterEffectsManager;
  ArkRepairable m_repairable;
  ArkGlooEffectTimed m_glooEffects;
  ArkUnanimous m_aiEnabled;
  ArkUnanimous m_attentionObjectEnabled;
  ArkUnanimous m_animationEnabled;
  ArkUnanimous m_dialogEnabled;
  ArkTurretUtils::TurretAngle m_curAngle;
  ArkTurretUtils::TurretAngle m_goalAngle;
  ArkTurretUtils::TurretAngle m_maxAcceleration;
  ArkTurretUtils::TurretAngle m_maxVelocity;
  ArkTurretUtils::TurretAngle m_velocity;
  float m_yawLimit;
  float m_pitchLowerLimit;
  float m_pitchUpperLimit;
  float m_angularVelDamp;
  unsigned int m_controllingTechnopathId;
  unsigned int m_flowgraphTargetId;
  Vec3_tpl<float> m_flowgraphTargetPos;
  Vec3_tpl<float> m_deployedBoundingBoxSize;
  unsigned int m_turretDefaultFactionIndex;
  unsigned int m_turretPlayerControlledFactionIndex;
  unsigned int m_turretHackedFactionIndex;
  ArkAudioTrigger m_audioTriggers[12];
  IActionController *m_pActionController;
  SAnimationContext *m_pAnimContex;
  const IAnimationDatabase *m_pAnimationDB;
  std::shared_ptr<IAnimationOperatorQueue> m_pAimRotationModifier;
  ArkSimpleTimer m_acquiredLineOfSightTimer;
  ArkSimpleTimer m_lostLineOfSightTimer;
  ArkSimpleTimer m_stunnedTimer;
  ArkSimpleTimer m_machineMindControlTimer;
  ArkSimpleTimer m_playerBumpTimer;
  ArkSimpleTimer m_holdUseTimer;
  unsigned __int64 m_technoControlledSignalModifier;
  unsigned __int64 m_callForHelpNoiseType;
  unsigned __int64 m_callForHelpLoudness;
  ArkSpatialManagerEntry<ArkSpatialManagerEntryImpl_Turret> m_spatialManagerEntry;
  const char *m_pLootInteractionText;
  const char *m_pDeployInteractionText;
  const char *m_pCantDeployInteractionText;
  float m_deadCarryHoldUseDuration;
  float m_fCloseThresholdAutoDisable;
  unsigned __int64 m_fallDamagePackageId;
  float m_fallStartHeight;
  float m_fallMinSpeedForFalling;
  float m_fallDistanceForDamage;
  float m_fallDamagePerMeter;
  __int16 m_gimbalYawJointID;
  __int16 m_gimbalPitchJointID;
  __int16 m_barrelEndJointID;
  __int16 m_barrelStockJointID;
  bool m_bIsFlowControlling;
  bool m_bHasFlowgraphTarget;
  bool m_bFlowgraphRequestShooting;
  bool m_bUndeployedPickupMode;
  bool m_bIsManuallyAiming;
  bool m_bIsActive;
  bool m_bAttentionObjectEnabled;
  bool m_bAnimationEnabled;
  bool m_bAiEnabled;
  bool m_bHacked;
  bool m_bIsMachineMinded;
  bool m_bIsStunned;
  bool m_bIsMimickedByPlayer;
  bool m_bIsFalling;
  bool m_bIsInZeroG;
};
