Script.ReloadScript("Scripts/Entities/Ark/Pickups/ArkItem.lua")
ArkWeaponShotgun = {
  Properties = {
    object_GeometryFP = "Objects/weapons/Shotgun/1P/Shotgun1P.cdf",
    object_GeometryTP = "Objects/weapons/Shotgun/3P/shotgun3p_01.cgf",
    bEquippable = 1,
    fLerpSpeed = 10,
    Description = {
      baseDamageKeyword = "",
      finalDamageKeyword = "",
      signal_damageSignal = ""
    },
    Weapon = {
      playerImpulse = 1,
      playerImpulseZeroG = 1,
      fAmmoLootImpulse = 0.8,
      recoilPitchMin = 0,
      recoilPitchMax = 0,
      recoilYawMin = 0,
      recoilYawMax = 0,
      recoilDuration = 0,
      recoilDelay = 0,
      anim_Animation = "Animations/Mannequin/ADB/ArkWeaponShotgun1P.adb",
      sAnimTag = "shotgun",
      sAttachmentName = "weapon",
      archetype_ammo = "ArkProjectiles.Bullets.ShotgunPellet_Default",
      sAmmoSpawnPointName = "muzzle",
      particleEffect_MuzzleLight = "PlayerWeapons.Shotgun.MuzzleFlash_SingleLight_00",
      sMuzzleLightAttachment = "muzzle",
      fAimRange = 3,
      fBaseAmmoCost = 1,
      nClipSize = 8,
      fReloadSpeed = 1,
      fRateOfAttack = 2,
      bAutoloadAmmo = 1,
      bAllowInterruptReloading = 1,
      nNumAmmoReloaded = 1,
      nInitialAmmoMin = 0,
      nInitialAmmoMax = 8,
      fCriticalShotChance = 0.1,
      bAffectedByDisruption = 0,
      fCombatFocusAmount = 0.1,
      fWalkSpeedMultiplier = 1,
      fCameraSpeedMultiplier = 1,
      fZoomedHFOV = 70,
      fZoomTime = 0.4,
      fZoomedWalkSpeedMultiplier = 0.5,
      fZoomedCameraSpeedMultiplier = 0.5,
      bUsesCrosshairReticle = 1,
      sUIElementName = "DanielleWeaponUI",
      nWeaponUIType = 1,
      fIdleBreakDelayTime = 8,
      fIronsightsTargetWidth = 1,
      fIronsightsTargetDistance = 10,
      fIronsightsTargetSpeed = 10,
      fIronsightsSuccessDistance = 0.1,
      fIronsightsMaxAngularVelocity = 450,
      fAimAssistRangeMax = 20,
      Degradation = {
        fDegradationRate = 1,
        fMalfunctionThreshold = 20,
        fMalfunctionRate = 12.5,
        sBrokenIcon = "",
        sBrokenHUDIcon = "",
        audioTrigger_StartMalfunction = "",
        audioTrigger_StopMalfunction = "",
        audioTrigger_Break = "",
        fHazardIconTime = 1,
        bTakeHazardDamage = 1,
        fMinStartCondition = 20,
        fMaxStartCondition = 50
      },
      sLeverageImpulseScaleBaseName = "Leverage Base",
      sLeverageImpulseScale1Name = "Leverage I",
      sLeverageImpulseScale2Name = "Leverage II",
      sLeverageImpulseScale3Name = "Leverage III",
      fLeverage0_ImpulseScale = 1,
      fLeverage1_ImpulseScale = 0,
      fLeverage2_ImpulseScale = 0,
      fLeverage3_ImpulseScale = 0,
      tutorial_firstTimePickup = "",
      tutorial_weaponCard = "",
      sUpgradeInfoDesc = "@ui_GunsmithRequired",
      Light = {
        sLightAttachmentName = "",
        archetype_LightArchetype = "",
        vector_DefaultLightColor = {
          x = 1,
          y = 1,
          z = 1
        },
        vector_DamagedLightColor = {
          x = 1,
          y = 1,
          z = 0
        },
        vector_BrokenLightColor = {
          x = 1,
          y = 0,
          z = 0
        }
      }
    },
    Shotgun = {
      nNumberOfPelletRows = 4,
      nNumberOfPelletColumns = 4,
      fAimRange = 3,
      fSpreadConeDegrees = 4.5,
      fAccurateShotChance = 0.1,
      fEffectiveRange = 10,
      fDamageDropoffPerMeter = 0.1,
      Dispersion = {
        fMinimum = 1,
        fMaximum = 3,
        fMinimumIronsights = 0.05,
        fMaximumIronsights = 2,
        fMinimumCrawling = 0.06,
        fMaximumCrawling = 2.25,
        fMinimumSneaking = 0.07,
        fMaximumSneaking = 2.75,
        fAmount_Recoil = 0.02,
        fRate_IronSights = -0.01,
        fAmount_Jumping = 0.01,
        fAmount_Sliding = 0.01,
        fRate_Turning = 0.002,
        fRate_NotTurning = -0.005,
        fRate_Moving = 0.002,
        fRate_NotMoving = -0.005,
        fRate_Sprinting = 0.005,
        fRate_Standing = 0,
        fRate_Crawling = 0.003,
        fRate_Sneaking = 0.007,
        fRate_ZeroG = 0.001
      },
      PointBlank = {
        fRange = 3,
        fRadius = 1,
        archetype_ammoType = "ArkProjectiles.Bullets.ShotgunBlast_Default",
        fHitDistance = 0.2,
        fImpulse = 10,
        maxImpulseMassScale = 50
      },
      DebugTesting = {fDebugDrawTime = 20, nNumTestPoints = 1000}
    }
  },
  PropertiesInstance = {iInitialAmmo = 4, fStartingConditionOverride = -1}
}
ArkMakeDerivedEntityOverride(ArkWeaponShotgun, ArkItem, true)
