Script.ReloadScript("SCRIPTS/Entities/AI/Ark/ArkOperatorMilitary_x.lua")
Script.ReloadScript("SCRIPTS/Entities/actor/BasicActor.lua")
Script.ReloadScript("SCRIPTS/Entities/AI/Shared/BasicAI.lua")
Script.ReloadScript("SCRIPTS/Entities/actor/ArkNpc.lua")
Script.ReloadScript("SCRIPTS/Entities/AI/Ark/ArkOperator.lua")
CreateActorForAISubclass(ArkOperatorMilitary_x)
CreateArkNpc(ArkOperator_x)
ArkOperatorMilitary = CreateAISubclass(ArkOperatorMilitary_x, ArkOperator_x)
InitActorForAISubclass(ArkOperatorMilitary_x)
ArkOperatorMilitary:Expose()
