Script.ReloadScript("SCRIPTS/Entities/AI/Ark/ArkPhantomVoltaic_x.lua")
Script.ReloadScript("SCRIPTS/Entities/actor/BasicActor.lua")
Script.ReloadScript("SCRIPTS/Entities/AI/Shared/BasicAI.lua")
Script.ReloadScript("SCRIPTS/Entities/actor/ArkNpc.lua")
Script.ReloadScript("SCRIPTS/Entities/AI/Ark/ArkBeta.lua")
CreateActorForAISubclass(ArkPhantomVoltaic_x)
CreateArkNpc(ArkBeta_x)
ArkPhantomVoltaic = CreateAISubclass(ArkPhantomVoltaic_x, ArkBeta_x)
InitActorForAISubclass(ArkPhantomVoltaic_x)
ArkPhantomVoltaic:Expose()
