Script.ReloadScript("SCRIPTS/Entities/AI/Ark/ArkMimic_x.lua")
Script.ReloadScript("SCRIPTS/Entities/actor/BasicActor.lua")
Script.ReloadScript("SCRIPTS/Entities/AI/Shared/BasicAI.lua")
Script.ReloadScript("SCRIPTS/Entities/actor/ArkNpc.lua")
CreateActor(ArkMimic_x)
CreateArkNpc(ArkMimic_x)
ArkMimic = CreateAI(ArkMimic_x)
ArkMimic:Expose()
