Script.ReloadScript("SCRIPTS/Entities/AI/Ark/ArkOperatorEngineer_x.lua")
Script.ReloadScript("SCRIPTS/Entities/actor/BasicActor.lua")
Script.ReloadScript("SCRIPTS/Entities/AI/Shared/BasicAI.lua")
Script.ReloadScript("SCRIPTS/Entities/actor/ArkNpc.lua")
Script.ReloadScript("SCRIPTS/Entities/AI/Ark/ArkOperator.lua")
CreateActorForAISubclass(ArkOperatorEngineer_x)
CreateArkNpc(ArkOperator_x)
ArkOperatorEngineer = CreateAISubclass(ArkOperatorEngineer_x, ArkOperator_x)
InitActorForAISubclass(ArkOperatorEngineer_x)
ArkOperatorEngineer:Expose()
