Script.ReloadScript("SCRIPTS/Entities/AI/Ark/ArkOperatorScience_x.lua")
Script.ReloadScript("SCRIPTS/Entities/actor/BasicActor.lua")
Script.ReloadScript("SCRIPTS/Entities/AI/Shared/BasicAI.lua")
Script.ReloadScript("SCRIPTS/Entities/actor/ArkNpc.lua")
Script.ReloadScript("SCRIPTS/Entities/AI/Ark/ArkOperator.lua")
CreateActorForAISubclass(ArkOperatorScience_x)
CreateArkNpc(ArkOperator_x)
ArkOperatorScience = CreateAISubclass(ArkOperatorScience_x, ArkOperator_x)
InitActorForAISubclass(ArkOperatorScience_x)
ArkOperatorScience:Expose()
