// Auto-merged (both): base=PreyDll under #ifndef MOONCRASH; DLC=Mooncrash.
#ifndef MOONCRASH
#pragma once
struct ICVar;
struct IConsole;
struct IConsoleCmdArgs;

// Header: FromCpp
// CryEngine/renderdll/common/renderercvars.h
class CRendererCVars // Id=80106E2 Size=88
{
public:
	static inline auto CV_r_ShowDynTexturesFilter = PreyGlobal<ICVar*>(0x2B0EFB0);
	static inline auto CV_r_ShaderCompilerServer = PreyGlobal<ICVar*>(0x2B0EFB8);
	static inline auto CV_r_ShaderCompilerFolderName = PreyGlobal<ICVar*>(0x2B0EFC0);
	static inline auto CV_r_ShaderCompilerFolderSuffix = PreyGlobal<ICVar*>(0x2B0EFC8);
	static inline auto CV_r_ShaderEmailTags = PreyGlobal<ICVar*>(0x2B0EFD0);
	static inline auto CV_r_ShaderEmailCCs = PreyGlobal<ICVar*>(0x2B0EFD8);
	static inline auto CV_r_excludeshader = PreyGlobal<ICVar*>(0x2B0EFE0);
	static inline auto CV_r_excludemesh = PreyGlobal<ICVar*>(0x2B0EFE8);
	static inline auto CV_r_ShowTexture = PreyGlobal<ICVar*>(0x2B0EFF0);
	static inline auto CV_r_TexturesStreamingDebugfilter = PreyGlobal<ICVar*>(0x2B0EFF8);
	static inline auto CV_r_vsync = PreyGlobal<int>(0x2B0EFAC);
	static inline auto CV_r_overrideRefreshRate = PreyGlobal<float>(0x2B0F000);
	static inline auto CV_r_overrideScanlineOrder = PreyGlobal<int>(0x2B0F004);
	static inline auto CV_r_overrideDXGIOutput = PreyGlobal<int>(0x2B0F008);
	static inline auto CV_r_FullscreenPreemption = PreyGlobal<int>(0x226BCA4);
	static inline auto CV_r_SyncToFrameFence = PreyGlobal<int>(0x2B0F00C);
	static inline auto CV_r_GraphicsPipeline = PreyGlobal<int>(0x2B0E958);
	static inline auto CV_r_DeferredShadingTiled = PreyGlobal<int>(0x2B0E95C);
	static inline auto CV_r_DeferredShadingTiledDebug = PreyGlobal<int>(0x2B0E960);
	static inline auto CV_r_DeferredShadingTiledHairQuality = PreyGlobal<int>(0x2B0E964);
	static inline auto CV_r_DeferredShadingSSS = PreyGlobal<int>(0x2B0E968);
	static inline auto CV_r_MotionVectors = PreyGlobal<int>(0x2B0E96C);
	static inline auto CV_r_MotionBlur = PreyGlobal<int>(0x2B0E970);
	static inline auto CV_r_MotionBlurQuality = PreyGlobal<int>(0x2B0E974);
	static inline auto CV_r_MotionBlurGBufferVelocity = PreyGlobal<int>(0x2B0E978);
	static inline auto CV_r_MotionBlurThreshold = PreyGlobal<float>(0x2B0E97C);
	static inline auto CV_r_minimizeLatency = PreyGlobal<int>(0x2B0E980);
	static inline auto CV_r_DeferredShadingAmbientSClear = PreyGlobal<int>(0x2B0E984);
	static inline auto CV_r_batchtype = PreyGlobal<int>(0x2B0E988);
	static inline auto CV_r_SilhouettePOM = PreyGlobal<int>(0x2B0E98C);
	static inline auto CV_r_WaterTessellationHW = PreyGlobal<int>(0x2B0E990);
	static inline auto CV_r_tessellationdebug = PreyGlobal<int>(0x2B0E994);
	static inline auto CV_r_tessellationtrianglesize = PreyGlobal<float>(0x2B0E998);
	static inline auto CV_r_displacementfactor = PreyGlobal<float>(0x2B0E99C);
	static inline auto CV_r_geominstancingthreshold = PreyGlobal<int>(0x2B0E9A0);
	static inline auto CV_r_ShadowsDepthBoundNV = PreyGlobal<int>(0x2B0E9A4);
	static inline auto CV_r_ShadowsPCFiltering = PreyGlobal<int>(0x2B0E9A8);
	static inline auto CV_r_rc_autoinvoke = PreyGlobal<int>(0x2B0E9AC);
	static inline auto CV_r_Refraction = PreyGlobal<int>(0x2B0E9B0);
	static inline auto CV_r_PostProcessReset = PreyGlobal<int>(0x2B0E9B4);
	static inline auto CV_r_colorRangeCompression = PreyGlobal<int>(0x2B0E9B8);
	static inline auto CV_r_colorgrading_selectivecolor = PreyGlobal<int>(0x2B0E9BC);
	static inline auto CV_r_colorgrading_charts = PreyGlobal<int>(0x2B0E9C0);
	static inline auto CV_r_ColorgradingChartsCache = PreyGlobal<int>(0x2B0E9C4);
	static inline auto CV_r_ShaderCompilerPort = PreyGlobal<int>(0x2B0E9C8);
	static inline auto CV_r_ShowDynTexturesMaxCount = PreyGlobal<int>(0x2B0E9CC);
	static inline auto CV_r_ShaderCompilerDontCache = PreyGlobal<int>(0x2B0E9D0);
	static inline auto CV_r_dyntexmaxsize = PreyGlobal<int>(0x2B0E9D4);
	static inline auto CV_r_texmaxanisotropy = PreyGlobal<int>(0x2B0E9D8);
	static inline auto CV_r_texturesskiplowermips = PreyGlobal<int>(0x2B0E9DC);
	static inline auto CV_r_rendertargetpoolsize = PreyGlobal<int>(0x2B0E9E0);
	static inline auto CV_r_texturesstreamingsync = PreyGlobal<int>(0x2B0E9E4);
	static inline auto CV_r_watercausticsdeferred = PreyGlobal<int>(0x2B0E9E8);
	static inline auto CV_r_WaterUpdateThread = PreyGlobal<int>(0x2B0E9EC);
	static inline auto CV_r_watercaustics = PreyGlobal<int>(0x2B0E9F0);
	static inline auto CV_r_watervolumecaustics = PreyGlobal<int>(0x2B0E9F4);
	static inline auto CV_r_watervolumecausticsdensity = PreyGlobal<int>(0x2B0E9F8);
	static inline auto CV_r_watervolumecausticsresolution = PreyGlobal<int>(0x2B0E9FC);
	static inline auto CV_r_shaderspreactivate = PreyGlobal<int>(0x2B0EA00);
	static inline auto CV_r_shadersremotecompiler = PreyGlobal<int>(0x2B0EA04);
	static inline auto CV_r_shadersasynccompiling = PreyGlobal<int>(0x2B0EA08);
	static inline auto CV_r_shadersasyncactivation = PreyGlobal<int>(0x2B0EA0C);
	static inline auto CV_r_shadersasyncmaxthreads = PreyGlobal<int>(0x2B0EA10);
	static inline auto CV_r_shaderscachedeterministic = PreyGlobal<int>(0x2B0EA14);
	static inline auto CV_r_shaderssubmitrequestline = PreyGlobal<int>(0x2B0EA18);
	static inline auto CV_r_shaderslogcachemisses = PreyGlobal<int>(0x2B0EA1C);
	static inline auto CV_r_meshpoolsize = PreyGlobal<int>(0x2B0EA20);
	static inline auto CV_r_meshinstancepoolsize = PreyGlobal<int>(0x2B0EA24);
	static inline auto CV_r_multigpu = PreyGlobal<int>(0x2B0EA28);
	static inline auto CV_r_beams = PreyGlobal<int>(0x2B0EA2C);
	static inline auto CV_r_nodrawnear = PreyGlobal<int>(0x2B0EA30);
	static inline auto CV_r_DrawNearShadows = PreyGlobal<int>(0x2B0EA34);
	static inline auto CV_r_scissor = PreyGlobal<int>(0x2B0EA38);
	static inline auto CV_r_usezpass = PreyGlobal<int>(0x2B0EA3C);
	static inline auto CV_r_ShowVideoMemoryStats = PreyGlobal<int>(0x2B0EA40);
	static inline auto CV_r_TexturesStreamingDebugMinSize = PreyGlobal<int>(0x2B0EA44);
	static inline auto CV_r_TexturesStreamingDebugMinMip = PreyGlobal<int>(0x2B0EA48);
	static inline auto CV_r_enableAltTab = PreyGlobal<int>(0x2B0EA4C);
	static inline auto CV_r_DynTexSourceSharedRTWidth = PreyGlobal<int>(0x2B0EA50);
	static inline auto CV_r_DynTexSourceSharedRTHeight = PreyGlobal<int>(0x2B0EA54);
	static inline auto CV_r_DynTexSourceUseSharedRT = PreyGlobal<int>(0x2B0EA58);
	static inline auto CV_r_ScreenShotFileName = PreyGlobal<ICVar*>(0x2B0EA60);
	static inline auto CV_r_GetScreenShot = PreyGlobal<int>(0x2B0EA5C);
	static inline auto CV_r_BreakOnError = PreyGlobal<int>(0x2B0EA68);
	static inline auto CV_r_TexturesStreamPoolSize = PreyGlobal<int>(0x2B0EA6C);
	static inline auto CV_r_TexturesStreamPoolSecondarySize = PreyGlobal<int>(0x2B0EA70);
	static inline auto CV_r_ReprojectOnlyStaticObjects = PreyGlobal<int>(0x2B0EA74);
	static inline auto CV_r_ReadZBufferDirectlyFromVMEM = PreyGlobal<int>(0x2B0EA78);
	static inline auto CV_r_durango_async_dips = PreyGlobal<int>(0x2B0EA7C);
	static inline auto CV_r_durango_async_dips_sync = PreyGlobal<int>(0x2B0EA80);
	static inline auto CV_r_D3D12SubmissionThread = PreyGlobal<int>(0x2B0EA84);
	static inline auto CV_r_D3D12WaitableSwapChain = PreyGlobal<int>(0x2B0EA88);
	static inline auto CV_r_D3D12BatchResourceBarriers = PreyGlobal<int>(0x2B0EA8C);
	static inline auto CV_r_D3D12EarlyResourceBarriers = PreyGlobal<int>(0x2B0EA90);
	static inline auto CV_r_D3D12AsynchronousCompute = PreyGlobal<int>(0x2B0EA94);
	static inline auto CV_r_D3D12HardwareComputeQueue = PreyGlobal<int>(0x2B0EA98);
	static inline auto CV_r_D3D12HardwareCopyQueue = PreyGlobal<int>(0x2B0EA9C);
	static inline auto CV_r_ReverseDepth = PreyGlobal<int>(0x2B0EAA0);
	static inline auto CV_r_EnableDebugLayer = PreyGlobal<int>(0x2B0EAA4);
	static inline auto CV_r_NoDraw = PreyGlobal<int>(0x2B0EAA8);
	static inline auto CV_r_UpdateInstances = PreyGlobal<int>(0x2B0EAAC);
	static inline auto CV_r_stats = PreyGlobal<int>(0x2B0EAB0);
	static inline auto CV_r_statsMinDrawcalls = PreyGlobal<int>(0x2B0EAB4);
	static inline auto CV_r_profiler = PreyGlobal<int>(0x2B0EAB8);
	static inline auto CV_r_profilerTargetFPS = PreyGlobal<float>(0x2B0EABC);
	static inline auto CV_r_LightPropagationVolumes = PreyGlobal<int>(0x2B0EAC0);
	static inline auto CV_r_ShadowPoolMaxFrames = PreyGlobal<int>(0x2B0EAC4);
	static inline auto CV_r_predicatedtiling = PreyGlobal<int>(0x2B0EAC8);
	static inline auto CV_r_useESRAM = PreyGlobal<int>(0x2B0EACC);
	static inline auto CV_r_multithreaded = PreyGlobal<int>(0x2B0EAD0);
	static inline auto CV_r_multithreadedDrawing = PreyGlobal<int>(0x2B0EAD4);
	static inline auto CV_r_multithreadedDrawingCoalesceMode = PreyGlobal<int>(0x2B0EAD8);
	static inline auto CV_r_multithreadedDrawingMinNonJobs = PreyGlobal<int>(0x2B0EADC);
	static inline auto CV_r_multithreadedDrawingMinJobSize = PreyGlobal<int>(0x2B0EAE0);
	static inline auto CV_r_deferredshadingLightVolumes = PreyGlobal<int>(0x2B0EAE4);
	static inline auto CV_r_deferredDecals = PreyGlobal<int>(0x2B0EAE8);
	static inline auto CV_r_deferredDecalsDebug = PreyGlobal<int>(0x2B0EAEC);
	static inline auto CV_r_DeferredShadingScissor = PreyGlobal<int>(0x2B0EAF0);
	static inline auto CV_r_DeferredShadingDebug = PreyGlobal<int>(0x2B0EAF4);
	static inline auto CV_r_DeferredShadingDebugGBuffer = PreyGlobal<int>(0x2B0EAF8);
	static inline auto CV_r_DeferredShadingEnvProbes = PreyGlobal<int>(0x2B0EAFC);
	static inline auto CV_r_DeferredShadingAmbient = PreyGlobal<int>(0x2B0EB00);
	static inline auto CV_r_DeferredShadingAmbientLights = PreyGlobal<int>(0x2B0EB04);
	static inline auto CV_r_DeferredShadingLights = PreyGlobal<int>(0x2B0EB08);
	static inline auto CV_r_DeferredShadingAreaLights = PreyGlobal<int>(0x2B0EB0C);
	static inline auto CV_r_DeferredShadingTiledLightsPriority = PreyGlobal<int>(0x2B0EB10);
	static inline auto CV_r_DeferredShadingGameplayLightBias = PreyGlobal<float>(0x2B0EB14);
	static inline auto CV_r_DeferredShadingStencilPrepass = PreyGlobal<int>(0x2B0EB18);
	static inline auto CV_r_PixelOutputMode = PreyGlobal<int>(0x2B0EB1C);
	static inline auto CV_r_HDRRendering = PreyGlobal<int>(0x2B0EB20);
	static inline auto CV_r_HDRDebug = PreyGlobal<int>(0x2B0EB24);
	static inline auto CV_r_HDRBloom = PreyGlobal<int>(0x2B0EB28);
	static inline auto CV_r_HDRBloomQuality = PreyGlobal<int>(0x2B0EB2C);
	static inline auto CV_r_HDRVignetting = PreyGlobal<int>(0x2B0EB30);
	static inline auto CV_r_HDRTexFormat = PreyGlobal<int>(0x2B0EB34);
	static inline auto CV_r_HDRRangeAdapt = PreyGlobal<int>(0x2B0EB38);
	static inline auto CV_r_HDREyeAdaptationMode = PreyGlobal<int>(0x2B0EB3C);
	static inline auto CV_r_geominstancing = PreyGlobal<int>(0x2B0EB40);
	static inline auto CV_r_geominstancingdebug = PreyGlobal<int>(0x2B0EB44);
	static inline auto CV_r_materialsbatching = PreyGlobal<int>(0x2B0EB48);
	static inline auto CV_r_UseShadowsPool = PreyGlobal<int>(0x2B0EB4C);
	static inline auto CV_r_shadowtexformat = PreyGlobal<int>(0x2B0EB50);
	static inline auto CV_r_ShadowsMaskResolution = PreyGlobal<int>(0x2B0EB54);
	static inline auto CV_r_ShadowsMaskDownScale = PreyGlobal<int>(0x2B0EB58);
	static inline auto CV_r_CBufferUseNativeDepth = PreyGlobal<int>(0x2B0EB5C);
	static inline auto CV_r_ShadowsStencilPrePass = PreyGlobal<int>(0x2B0EB60);
	static inline auto CV_r_ShadowMaskStencilPrepass = PreyGlobal<int>(0x2B0EB64);
	static inline auto CV_r_ShadowsGridAligned = PreyGlobal<int>(0x2B0EB68);
	static inline auto CV_r_ShadowPass = PreyGlobal<int>(0x2B0EB6C);
	static inline auto CV_r_ShadowGen = PreyGlobal<int>(0x2B0EB70);
	static inline auto CV_r_ShadowGenDepthClip = PreyGlobal<int>(0x2B0EB74);
	static inline auto CV_r_ShadowsUseClipVolume = PreyGlobal<int>(0x2B0EB78);
	static inline auto CV_r_shadowblur = PreyGlobal<int>(0x2B0EB7C);
	static inline auto CV_r_ShadowGenMode = PreyGlobal<int>(0x2B0EB80);
	static inline auto CV_r_ShadowsCache = PreyGlobal<int>(0x2B0EB84);
	static inline auto CV_r_ShadowsCacheFormat = PreyGlobal<int>(0x2B0EB88);
	static inline auto CV_r_ShadowsNearestMapResolution = PreyGlobal<int>(0x2B0EB8C);
	static inline auto CV_r_ShadowsScreenSpace = PreyGlobal<int>(0x2B0EB90);
	static inline auto CV_r_deferredshadingDBTstencil = PreyGlobal<int>(0x2B0EB94);
	static inline auto CV_r_sunshafts = PreyGlobal<int>(0x2B0EB98);
	static inline auto CV_r_MergeShadowDrawcalls = PreyGlobal<int>(0x2B0EB9C);
	static inline auto CV_r_PostProcess_CB = PreyGlobal<int>(0x2B0EBA0);
	static inline auto CV_r_PostProcess = PreyGlobal<int>(0x2B0EBA4);
	static inline auto CV_r_PostProcessFilters = PreyGlobal<int>(0x2B0EBA8);
	static inline auto CV_r_PostProcessGameFx = PreyGlobal<int>(0x2B0EBAC);
	static inline auto CV_r_PostProcessParamsBlending = PreyGlobal<int>(0x2B0EBB0);
	static inline auto CV_r_colorgrading = PreyGlobal<int>(0x2B0EBB4);
	static inline auto CV_r_colorgrading_levels = PreyGlobal<int>(0x2B0EBB8);
	static inline auto CV_r_colorgrading_filters = PreyGlobal<int>(0x2B0EBBC);
	static inline auto CV_r_showdyntextures = PreyGlobal<int>(0x2B0EBC0);
	static inline auto CV_r_shownormals = PreyGlobal<int>(0x2B0EBC4);
	static inline auto CV_r_showlines = PreyGlobal<int>(0x2B0EBC8);
	static inline auto CV_r_showtangents = PreyGlobal<int>(0x2B0EBCC);
	static inline auto CV_r_showtimegraph = PreyGlobal<int>(0x2B0EBD0);
	static inline auto CV_r_DebugFontRendering = PreyGlobal<int>(0x2B0EBD4);
	static inline auto CV_profileStreaming = PreyGlobal<int>(0x2B0EBD8);
	static inline auto CV_r_graphstyle = PreyGlobal<int>(0x2B0EBDC);
	static inline auto CV_r_showbufferusage = PreyGlobal<int>(0x2B0EBE0);
	static inline auto CV_r_ProfileShadersSmooth = PreyGlobal<int>(0x2B0EBE4);
	static inline auto CV_r_ProfileShadersGroupByName = PreyGlobal<int>(0x2B0EBE8);
	static inline auto CV_r_texpostponeloading = PreyGlobal<int>(0x2B0EBEC);
	static inline auto CV_r_texlog = PreyGlobal<int>(0x2B0EBF0);
	static inline auto CV_r_texnoload = PreyGlobal<int>(0x2B0EBF4);
	static inline auto CV_r_texturecompiling = PreyGlobal<int>(0x2B0EBF8);
	static inline auto CV_r_texturecompilingIndicator = PreyGlobal<int>(0x2B0EBFC);
	static inline auto CV_r_texturesstreaming = PreyGlobal<int>(0x2B0EC00);
	static inline auto CV_r_TexturesStreamingDebug = PreyGlobal<int>(0x2B0EC04);
	static inline auto CV_r_texturesstreamingnoupload = PreyGlobal<int>(0x2B0EC08);
	static inline auto CV_r_texturesstreamingonlyvideo = PreyGlobal<int>(0x2B0EC0C);
	static inline auto CV_r_texturesstreamingmipfading = PreyGlobal<int>(0x2B0EC10);
	static inline auto CV_r_texturesstreamingUpdateType = PreyGlobal<int>(0x2B0EC14);
	static inline auto CV_r_texturesstreamingPrecacheRounds = PreyGlobal<int>(0x2B0EC18);
	static inline auto CV_r_texturesstreamingSuppress = PreyGlobal<int>(0x2B0EC1C);
	static inline auto CV_r_texturesstreamingSkipMips = PreyGlobal<int>(0x2B0EC20);
	static inline auto CV_r_texturesstreamingMinUsableMips = PreyGlobal<int>(0x2B0EC24);
	static inline auto CV_r_texturesstreamingJobUpdate = PreyGlobal<int>(0x2B0EC28);
	static inline auto CV_r_texturesstreamingDeferred = PreyGlobal<int>(0x2B0EC2C);
	static inline auto CV_r_texturesstreamingPostponeMips = PreyGlobal<int>(0x2B0EC30);
	static inline auto CV_r_texturesstreamingPostponeThresholdMip = PreyGlobal<int>(0x2B0EC34);
	static inline auto CV_r_texturesstreamingMinReadSizeKB = PreyGlobal<int>(0x2B0EC38);
	static inline auto CV_r_envtexresolution = PreyGlobal<int>(0x2B0EC3C);
	static inline auto CV_r_waterreflections_mgpu = PreyGlobal<int>(0x2B0EC40);
	static inline auto CV_r_waterreflections_use_min_offset = PreyGlobal<int>(0x2B0EC44);
	static inline auto CV_r_waterreflections = PreyGlobal<int>(0x2B0EC48);
	static inline auto CV_r_waterreflections_quality = PreyGlobal<int>(0x2B0EC4C);
	static inline auto CV_r_water_godrays = PreyGlobal<int>(0x2B0EC50);
	static inline auto CV_r_reflections = PreyGlobal<int>(0x2B0EC54);
	static inline auto CV_r_reflections_quality = PreyGlobal<int>(0x2B0EC58);
	static inline auto CV_r_dof = PreyGlobal<int>(0x2B0EC5C);
	static inline auto CV_r_texNoAnisoAlphaTest = PreyGlobal<int>(0x2B0EC60);
	static inline auto CV_r_reloadshaders = PreyGlobal<int>(0x2B0EC64);
	static inline auto CV_r_detailtextures = PreyGlobal<int>(0x2B0EC68);
	static inline auto CV_r_texbindmode = PreyGlobal<int>(0x2B0EC6C);
	static inline auto CV_r_nodrawshaders = PreyGlobal<int>(0x2B0EC70);
	static inline auto CV_r_shadersdebug = PreyGlobal<int>(0x2B0EC74);
	static inline auto CV_r_shadersignoreincludeschanging = PreyGlobal<int>(0x2B0EC78);
	static inline auto CV_r_shaderslazyunload = PreyGlobal<int>(0x2B0EC7C);
	static inline auto CV_r_shadersAllowCompilation = PreyGlobal<int>(0x2B0EC80);
	static inline auto CV_r_shaderscompileautoactivate = PreyGlobal<int>(0x2B0EC84);
	static inline auto CV_r_shadersediting = PreyGlobal<int>(0x2B0EC88);
	static inline auto CV_r_ReflectTextureSlots = PreyGlobal<int>(0x2B0EC8C);
	static inline auto CV_r_debugrendermode = PreyGlobal<int>(0x2B0EC90);
	static inline auto CV_r_debugrefraction = PreyGlobal<int>(0x2B0EC94);
	static inline auto CV_r_meshprecache = PreyGlobal<int>(0x2B0EC98);
	static inline auto CV_r_validateDraw = PreyGlobal<int>(0x2B0EC9C);
	static inline auto CV_r_flares = PreyGlobal<int>(0x226BCA0);
	static inline auto CV_r_flareHqShafts = PreyGlobal<int>(0x2B0ECA0);
	static inline auto CV_r_ZPassDepthSorting = PreyGlobal<int>(0x2B0ECA4);
	static inline auto CV_r_TransparentPasses = PreyGlobal<int>(0x2B0ECA8);
	static inline auto CV_r_SkipAlphaTested = PreyGlobal<int>(0x2B0ECAC);
	static inline auto CV_r_TranspDepthFixup = PreyGlobal<int>(0x2B0ECB0);
	static inline auto CV_r_usehwskinning = PreyGlobal<int>(0x2B0ECB4);
	static inline auto CV_r_ParticlesSoftIsec = PreyGlobal<int>(0x2B0ECB8);
	static inline auto CV_r_ParticlesRefraction = PreyGlobal<int>(0x2B0ECBC);
	static inline auto CV_r_ParticlesTessellation = PreyGlobal<int>(0x2B0ECC0);
	static inline auto CV_r_ParticlesTessellationTriSize = PreyGlobal<int>(0x2B0ECC4);
	static inline auto CV_r_ParticlesAmountGI = PreyGlobal<float>(0x2B0ECC8);
	static inline auto CV_r_ParticlesHalfRes = PreyGlobal<int>(0x2B0ECCC);
	static inline auto CV_r_ParticlesHalfResAmount = PreyGlobal<int>(0x2B0ECD0);
	static inline auto CV_r_ParticlesHalfResBlendMode = PreyGlobal<int>(0x2B0ECD4);
	static inline auto CV_r_ParticlesInstanceVertices = PreyGlobal<int>(0x2B0ECD8);
	static inline auto CV_r_AntialiasingModeEditor = PreyGlobal<int>(0x2B0ECDC);
	static inline auto CV_r_AntialiasingModeDebug = PreyGlobal<int>(0x2B0ECE0);
	static inline auto CV_r_rain = PreyGlobal<int>(0x2B0ECE4);
	static inline auto CV_r_rain_ignore_nearest = PreyGlobal<int>(0x2B0ECE8);
	static inline auto CV_r_snow = PreyGlobal<int>(0x2B0ECEC);
	static inline auto CV_r_snow_halfres = PreyGlobal<int>(0x2B0ECF0);
	static inline auto CV_r_snow_displacement = PreyGlobal<int>(0x2B0ECF4);
	static inline auto CV_r_snowFlakeClusters = PreyGlobal<int>(0x2B0ECF8);
	static inline auto CV_r_customvisions = PreyGlobal<int>(0x2B0ECFC);
	static inline auto CV_r_DofMode = PreyGlobal<int>(0x2B0ED00);
	static inline auto CV_r_DofBokehQuality = PreyGlobal<int>(0x2B0ED04);
	static inline auto CV_r_nohwgamma = PreyGlobal<int>(0x2B0ED08);
	static inline auto CV_r_wireframe = PreyGlobal<int>(0x2B0ED0C);
	static inline auto CV_r_printmemoryleaks = PreyGlobal<int>(0x2B0ED10);
	static inline auto CV_r_releaseallresourcesonexit = PreyGlobal<int>(0x2B0ED14);
	static inline auto CV_r_character_nodeform = PreyGlobal<int>(0x2B0ED18);
	static inline auto CV_r_ZPassOnly = PreyGlobal<int>(0x2B0ED1C);
	static inline auto CV_r_VegetationAlphaTestOnly = PreyGlobal<int>(0x2B0ED20);
	static inline auto CV_r_measureoverdraw = PreyGlobal<int>(0x2B0ED24);
	static inline auto CV_r_ShowLightBounds = PreyGlobal<int>(0x2B0ED28);
	static inline auto CV_r_MergeRenderChunks = PreyGlobal<int>(0x2B0ED2C);
	static inline auto CV_r_TextureCompressor = PreyGlobal<int>(0x2B0ED30);
	static inline auto CV_r_TexturesStreamingDebugDumpIntoLog = PreyGlobal<int>(0x2B0ED34);
	static inline auto CV_e_DebugTexelDensity = PreyGlobal<int>(0x2B0ED38);
	static inline auto CV_r_RefractionPartialResolves = PreyGlobal<int>(0x2B0ED3C);
	static inline auto CV_r_RefractionPartialResolvesDebug = PreyGlobal<int>(0x2B0ED40);
	static inline auto CV_r_Batching = PreyGlobal<int>(0x2B0ED44);
	static inline auto CV_r_Unlit = PreyGlobal<int>(0x2B0ED48);
	static inline auto CV_r_HideSunInCubemaps = PreyGlobal<int>(0x2B0ED4C);
	static inline auto CV_r_ParticlesDebug = PreyGlobal<int>(0x2B0ED50);
	static inline auto CV_e_DebugRenderMode = PreyGlobal<int>(0x2B0ED54);
	static inline auto CV_r_DebugAmbientEnable = PreyGlobal<int>(0x2B0ED58);
	static inline auto CV_r_ArkLateNearTransparency = PreyGlobal<int>(0x2B0ED5C);
	static inline auto CV_r_ArkStarsMoveWithSun = PreyGlobal<int>(0x2B0ED60);
	static inline auto CV_r_ArkStarOffsetPitch = PreyGlobal<float>(0x2B0ED64);
	static inline auto CV_r_ArkStarOffsetRoll = PreyGlobal<float>(0x2B0ED68);
	static inline auto CV_r_ArkStarOffsetYaw = PreyGlobal<float>(0x2B0ED6C);
	static inline auto CV_r_ZPrepassMaxDist = PreyGlobal<float>(0x2B0ED70);
	static inline auto CV_r_FlaresChromaShift = PreyGlobal<float>(0x2B0ED74);
	static inline auto CV_r_FlaresIrisShaftMaxPolyNum = PreyGlobal<int>(0x2B0ED78);
	static inline auto CV_r_FlaresTessellationRatio = PreyGlobal<float>(0x2B0ED7C);
	static inline auto CV_r_drawnearfov = PreyGlobal<float>(0x2B0ED80);
	static inline auto CV_r_measureoverdrawscale = PreyGlobal<float>(0x2B0ED84);
	static inline auto CV_r_DeferredShadingLightLodRatio = PreyGlobal<float>(0x2B0ED88);
	static inline auto CV_r_DeferredShadingLightStencilRatio = PreyGlobal<float>(0x2B0ED8C);
	static inline auto CV_r_rainDistMultiplier = PreyGlobal<float>(0x2B0ED90);
	static inline auto CV_r_rainOccluderSizeTreshold = PreyGlobal<float>(0x2B0ED94);
	static inline auto CV_r_HDRRangeAdaptMaxRange = PreyGlobal<float>(0x2B0ED98);
	static inline auto CV_r_HDRRangeAdaptMax = PreyGlobal<float>(0x2B0ED9C);
	static inline auto CV_r_HDRRangeAdaptLBufferMaxRange = PreyGlobal<float>(0x2B0EDA0);
	static inline auto CV_r_HDRRangeAdaptLBufferMax = PreyGlobal<float>(0x2B0EDA4);
	static inline auto CV_r_HDRRangeAdaptationSpeed = PreyGlobal<float>(0x2B0EDA8);
	static inline auto CV_r_HDREyeAdaptationSpeed = PreyGlobal<float>(0x2B0EDAC);
	static inline auto CV_r_HDRGrainAmount = PreyGlobal<float>(0x2B0EDB0);
	static inline auto CV_r_Sharpening = PreyGlobal<float>(0x2B0EDB4);
	static inline auto CV_r_ChromaticAberration = PreyGlobal<float>(0x2B0EDB8);
	static inline auto CV_r_dofMinZ = PreyGlobal<float>(0x2B0EDBC);
	static inline auto CV_r_dofMinZScale = PreyGlobal<float>(0x2B0EDC0);
	static inline auto CV_r_dofMinZBlendMult = PreyGlobal<float>(0x2B0EDC4);
	static inline auto CV_r_dofDilation = PreyGlobal<float>(0x2B0EDC8);
	static inline auto CV_r_ShadowsBias = PreyGlobal<float>(0x2B0EDCC);
	static inline auto CV_r_shadowbluriness = PreyGlobal<float>(0x2B0EDD0);
	static inline auto CV_r_ShadowsAdaptionRangeClamp = PreyGlobal<float>(0x2B0EDD4);
	static inline auto CV_r_ShadowsAdaptionSize = PreyGlobal<float>(0x2B0EDD8);
	static inline auto CV_r_ShadowsAdaptionMin = PreyGlobal<float>(0x2B0EDDC);
	static inline auto CV_r_ShadowsParticleKernelSize = PreyGlobal<float>(0x2B0EDE0);
	static inline auto CV_r_ShadowsParticleJitterAmount = PreyGlobal<float>(0x2B0EDE4);
	static inline auto CV_r_ShadowsParticleAnimJitterAmount = PreyGlobal<float>(0x2B0EDE8);
	static inline auto CV_r_ShadowsParticleNormalEffect = PreyGlobal<float>(0x2B0EDEC);
	static inline auto CV_r_shadow_jittering = PreyGlobal<float>(0x2B0EDF0);
	static inline auto CV_r_ShadowPoolMaxTimeslicedUpdatesPerFrame = PreyGlobal<int>(0x2B0EDF4);
	static inline auto CV_r_ShadowCastingLightsMaxCount = PreyGlobal<int>(0x2B0EDF8);
	static inline auto CV_r_RenderMeshHashGridUnitSize = PreyGlobal<float>(0x2B0EDFC);
	static inline auto CV_r_PostprocessParamsBlendingTimeScale = PreyGlobal<float>(0x2B0EE00);
	static inline auto CV_r_normalslength = PreyGlobal<float>(0x2B0EE04);
	static inline auto CV_r_TexelsPerMeter = PreyGlobal<float>(0x2B0EE08);
	static inline auto CV_r_TexturesStreamingMaxRequestedMB = PreyGlobal<float>(0x2B0EE0C);
	static inline auto CV_r_TexturesStreamingMaxRequestedJobs = PreyGlobal<int>(0x2B0EE10);
	static inline auto CV_r_TexturesStreamingMipBias = PreyGlobal<float>(0x2B0EE14);
	static inline auto CV_r_envtexupdateinterval = PreyGlobal<float>(0x2B0EE18);
	static inline auto CV_r_TextureLodDistanceRatio = PreyGlobal<float>(0x2B0EE1C);
	static inline auto CV_r_water_godrays_distortion = PreyGlobal<float>(0x2B0EE20);
	static inline auto CV_r_waterupdateFactor = PreyGlobal<float>(0x2B0EE24);
	static inline auto CV_r_waterupdateDistance = PreyGlobal<float>(0x2B0EE28);
	static inline auto CV_r_waterreflections_min_visible_pixels_update = PreyGlobal<float>(0x2B0EE2C);
	static inline auto CV_r_waterreflections_minvis_updatefactormul = PreyGlobal<float>(0x2B0EE30);
	static inline auto CV_r_waterreflections_minvis_updatedistancemul = PreyGlobal<float>(0x2B0EE34);
	static inline auto CV_r_waterreflections_offset = PreyGlobal<float>(0x2B0EE38);
	static inline auto CV_r_watercausticsdistance = PreyGlobal<float>(0x2B0EE3C);
	static inline auto CV_r_watervolumecausticssnapfactor = PreyGlobal<float>(0x2B0EE40);
	static inline auto CV_r_watervolumecausticsmaxdistance = PreyGlobal<float>(0x2B0EE44);
	static inline auto CV_r_detaildistance = PreyGlobal<float>(0x2B0EE48);
	static inline auto CV_r_DrawNearZRange = PreyGlobal<float>(0x2B0EE4C);
	static inline auto CV_r_DrawNearFarPlane = PreyGlobal<float>(0x2B0EE50);
	static inline auto CV_r_rainamount = PreyGlobal<float>(0x2B0EE54);
	static inline auto CV_r_MotionBlurShutterSpeed = PreyGlobal<float>(0x2B0EE58);
	static inline auto CV_r_MotionBlurCameraMotionScale = PreyGlobal<float>(0x2B0EE5C);
	static inline auto CV_r_MotionBlurMaxViewDist = PreyGlobal<float>(0x2B0EE60);
	static inline auto CV_r_gamma = PreyGlobal<float>(0x2B0EE64);
	static inline auto CV_r_contrast = PreyGlobal<float>(0x2B0EE68);
	static inline auto CV_r_brightness = PreyGlobal<float>(0x2B0EE6C);
	static inline auto CV_r_brightnessOffset = PreyGlobal<float>(0x2B0EE70);
	static inline auto CV_r_ZFightingDepthScale = PreyGlobal<float>(0x2B0EE74);
	static inline auto CV_r_ZFightingExtrude = PreyGlobal<float>(0x2B0EE78);
	static inline auto CV_r_FlashMatTexResQuality = PreyGlobal<float>(0x2B0EE7C);
	static inline auto CV_r_AntialiasingMode_CB = PreyGlobal<int>(0x2B0EE80);
	static inline auto CV_r_AntialiasingMode = PreyGlobal<int>(0x2B0EE84);
	static inline auto CV_r_AntialiasingModeSCull = PreyGlobal<int>(0x2B0EE88);
	static inline auto CV_r_AntialiasingTAAPattern = PreyGlobal<int>(0x2B0EE8C);
	static inline auto CV_r_AntialiasingTAAFalloffHiFreq = PreyGlobal<float>(0x2B0EE90);
	static inline auto CV_r_AntialiasingTAAFalloffLowFreq = PreyGlobal<float>(0x2B0EE94);
	static inline auto CV_r_AntialiasingTAASharpening = PreyGlobal<float>(0x2B0EE98);
	static inline auto CV_r_AntialiasingTSAAMipBias = PreyGlobal<float>(0x2B0EE9C);
	static inline auto CV_r_AntialiasingTSAASubpixelDetection = PreyGlobal<float>(0x2B0EEA0);
	static inline auto CV_r_AntialiasingTSAASmoothness = PreyGlobal<float>(0x2B0EEA4);
	static inline auto CV_r_FogDepthTest = PreyGlobal<float>(0x2B0EEA8);
	static inline auto CV_r_FogShadows = PreyGlobal<int>(0x2B0EEAC);
	static inline auto CV_r_FogShadowsMode = PreyGlobal<int>(0x2B0EEB0);
	static inline auto CV_r_FogShadowsWater = PreyGlobal<int>(0x2B0EEB4);
	static inline auto CV_r_rain_maxviewdist = PreyGlobal<float>(0x2B0EEB8);
	static inline auto CV_r_rain_maxviewdist_deferred = PreyGlobal<float>(0x2B0EEBC);
	static inline auto CV_r_SSReflections = PreyGlobal<int>(0x2B0EEC0);
	static inline auto CV_r_SSReflHalfRes = PreyGlobal<int>(0x2B0EEC4);
	static inline auto CV_r_ArkSSR = PreyGlobal<int>(0x2B0EEC8);
	static inline auto CV_r_ssdo = PreyGlobal<int>(0x2B0EECC);
	static inline auto CV_r_ssdoHalfRes = PreyGlobal<int>(0x2B0EED0);
	static inline auto CV_r_ssdoColorBleeding = PreyGlobal<int>(0x2B0EED4);
	static inline auto CV_r_ssdoRadius = PreyGlobal<float>(0x2B0EED8);
	static inline auto CV_r_ssdoRadiusMin = PreyGlobal<float>(0x2B0EEDC);
	static inline auto CV_r_ssdoRadiusMax = PreyGlobal<float>(0x2B0EEE0);
	static inline auto CV_r_ssdoAmountDirect = PreyGlobal<float>(0x2B0EEE4);
	static inline auto CV_r_ssdoAmountAmbient = PreyGlobal<float>(0x2B0EEE8);
	static inline auto CV_r_ssdoAmountReflection = PreyGlobal<float>(0x2B0EEEC);
	static inline auto CV_r_ArkSSDO = PreyGlobal<int>(0x2B0EEF0);
	static inline auto CV_r_CustomResMaxSize = PreyGlobal<int>(0x2B0EEF4);
	static inline auto CV_r_CustomResWidth = PreyGlobal<int>(0x2B0EEF8);
	static inline auto CV_r_CustomResHeight = PreyGlobal<int>(0x2B0EEFC);
	static inline auto CV_r_Supersampling = PreyGlobal<int>(0x2B0EF00);
	static inline auto CV_r_SupersamplingFilter = PreyGlobal<int>(0x2B0EF04);
	static inline auto CV_r_buffer_banksize = PreyGlobal<int>(0x2B0EF08);
	static inline auto CV_r_constantbuffer_banksize = PreyGlobal<int>(0x2B0EF0C);
	static inline auto CV_r_constantbuffer_watermark = PreyGlobal<int>(0x2B0EF10);
	static inline auto CV_r_transient_pool_size = PreyGlobal<int>(0x2B0EF14);
	static inline auto CV_r_buffer_enable_lockless_updates = PreyGlobal<int>(0x2B0EF18);
	static inline auto CV_r_enable_full_gpu_sync = PreyGlobal<int>(0x2B0EF1C);
	static inline auto CV_r_buffer_pool_max_allocs = PreyGlobal<int>(0x2B0EF20);
	static inline auto CV_r_buffer_pool_defrag_static = PreyGlobal<int>(0x2B0EF24);
	static inline auto CV_r_buffer_pool_defrag_static_shared = PreyGlobal<int>(0x2B0EF28);
	static inline auto CV_r_buffer_pool_defrag_dynamic = PreyGlobal<int>(0x2B0EF2C);
	static inline auto CV_r_buffer_pool_defrag_max_moves = PreyGlobal<int>(0x2B0EF30);
	static inline auto CV_r_ParticleVerticePoolSize = PreyGlobal<int>(0x2B0EF34);
	static inline auto CV_r_GeomCacheInstanceThreshold = PreyGlobal<int>(0x2B0EF38);
	static inline auto CV_r_VisAreaClipLightsPerPixel = PreyGlobal<int>(0x2B0EF3C);
	static inline auto CV_r_VolumetricFog = PreyGlobal<int>(0x2B0EF40);
	static inline auto CV_r_VolumetricFogPerFrame = PreyGlobal<int>(0x2B0EF44);
	static inline auto CV_r_VolumetricFogTexScale = PreyGlobal<int>(0x2B0EF48);
	static inline auto CV_r_VolumetricFogTexDepth = PreyGlobal<int>(0x2B0EF4C);
	static inline auto CV_r_VolumetricFogReprojectionBlendFactor = PreyGlobal<float>(0x2B0EF50);
	static inline auto CV_r_VolumetricFogSample = PreyGlobal<int>(0x2B0EF54);
	static inline auto CV_r_VolumetricFogShadow = PreyGlobal<int>(0x2B0EF58);
	static inline auto CV_r_VolumetricFogDownscaledSunShadow = PreyGlobal<int>(0x2B0EF5C);
	static inline auto CV_r_VolumetricFogDownscaledSunShadowRatio = PreyGlobal<int>(0x2B0EF60);
	static inline auto CV_r_VolumetricFogReprojectionMode = PreyGlobal<int>(0x2B0EF64);
	static inline auto CV_r_VolumetricFogMinimumLightBulbSize = PreyGlobal<float>(0x2B0EF68);
	static inline auto CV_r_VolumetricFogSunLightCorrection = PreyGlobal<int>(0x2B0EF6C);
	static inline auto CV_r_MorphFade = PreyGlobal<float>(0x2B0EF70);
	static inline auto CV_d3d11_CBUpdateStats = PreyGlobal<int>(0x2B0EF74);
	static inline auto CV_d3d11_forcedFeatureLevel = PreyGlobal<ICVar*>(0x2B0EF78);
	static inline auto CV_d3d11_preventDriverThreading = PreyGlobal<int>(0x2B0EF80);
	static inline auto CV_r_VolumetricClouds = PreyGlobal<int>(0x2B0EF84);
	static inline auto CV_r_VolumetricCloudsRaymarchStepNum = PreyGlobal<int>(0x2B0EF88);
	static inline auto CV_r_VolumetricCloudsPipeline = PreyGlobal<int>(0x2B0EF8C);
	static inline auto CV_r_VolumetricCloudsStereoReprojection = PreyGlobal<int>(0x2B0EF90);
	static inline auto CV_r_VolumetricCloudsTemporalReprojection = PreyGlobal<int>(0x2B0EF94);
	static inline auto CV_r_VolumetricCloudsShadowResolution = PreyGlobal<int>(0x2B0EF98);
	static inline auto CV_r_GpuParticles = PreyGlobal<int>(0x2B0EF9C);
	static inline auto CV_r_GpuParticlesConstantRadiusBoundingBoxes = PreyGlobal<int>(0x2B0EFA0);
	ICVar* CV_capture_frames;
	ICVar* CV_capture_folder;
	ICVar* CV_capture_file_format;
	ICVar* CV_capture_frame_once;
	ICVar* CV_capture_file_name;
	ICVar* CV_capture_file_prefix;
	ICVar* m_CVWidth;
	ICVar* m_CVHeight;
	ICVar* m_CVFullScreen;
	ICVar* m_CVColorBits;
	ICVar* m_CVDisplayInfo;
	static inline auto s_overscanBorders = PreyGlobal<Vec2>(0x2B0F010);
	static inline auto CV_r_LightBeamDepthPass = PreyGlobal<int>(0x2B0EFA4);
	static inline auto CV_r_EnableRenderDoc = PreyGlobal<int>(0x2B0EFA8);

	void InitCVars() { FInitCVars(this); }
	static void Cmd_ShowRenderTarget(IConsoleCmdArgs* pArgs) { FCmd_ShowRenderTarget(pArgs); }
	static void OnChange_CachedShadows(ICVar* pCVar) { FOnChange_CachedShadows(pCVar); }
	static void OnChange_GeomInstancingThreshold(ICVar* pVar) { FOnChange_GeomInstancingThreshold(pVar); }
	static void OnChange_ArkSSR(ICVar* _pVar) { FOnChange_ArkSSR(_pVar); }
	static void OnChange_ArkSSDO(ICVar* _pVar) { FOnChange_ArkSSDO(_pVar); }

#if 0
	static int GetTexturesStreamPoolSize();
	void InitExternalCVars();
	void CacheCaptureCVars();
#endif

	static inline auto FInitCVars = PreyFunction<void(CRendererCVars* const _this)>(0xE9AD50);
	static inline auto FCmd_ShowRenderTarget = PreyFunction<void(IConsoleCmdArgs* pArgs)>(0xE99BD0);
	static inline auto FOnChange_CachedShadows = PreyFunction<void(ICVar* pCVar)>(0xEA2560);
	static inline auto FOnChange_GeomInstancingThreshold = PreyFunction<void(ICVar* pVar)>(0xEA25A0);
	static inline auto FOnChange_ArkSSR = PreyFunction<void(ICVar* _pVar)>(0xEA2440);
	static inline auto FOnChange_ArkSSDO = PreyFunction<void(ICVar* _pVar)>(0xEA23F0);
};

static_assert(sizeof(CRendererCVars) == 88);

// CCVarUpdateRecorder
// Header:  CryEngine/renderdll/common/RendererCVars.h
// Include: Prey/RenderDll/Common/RendererCVars.h
class CCVarUpdateRecorder : public IConsoleVarSink
{ // Size=64 (0x40)
public:
	// CCVarUpdateRecorder::SUpdateRecord
	// Header:  CryEngine/renderdll/common/RendererCVars.h
	struct SUpdateRecord
	{ // Size=80 (0x50)
		union
		{
			int intValue;
			float floatValue;
			char stringValue[64];
		};

		const char* name;
		int type;

#if 0
		SUpdateRecord(ICVar* _arg0_);
#endif
	};

	using CVarList = std::vector<CCVarUpdateRecorder::SUpdateRecord>;

	std::vector<CCVarUpdateRecorder::SUpdateRecord> m_updatedCVars[2];
	IConsole* m_pConsole;

	CCVarUpdateRecorder(IConsole* pConsole);
	virtual ~CCVarUpdateRecorder();
	virtual bool OnBeforeVarChange(ICVar* pVar, const char* sNewValue);
	virtual void OnAfterVarChange(ICVar* pVar);
	void Reset() { FReset(this); }
	const std::vector<CCVarUpdateRecorder::SUpdateRecord>& GetCVars() const { return FGetCVars(this); }
	const CCVarUpdateRecorder::SUpdateRecord* GetCVar(const char* cvarName) const { return FGetCVar(this, cvarName); }

	static inline auto FCCVarUpdateRecorderOv1 = PreyFunction<void(CCVarUpdateRecorder* const _this, IConsole* pConsole)>(0xE99960);
	static inline auto FBitNotCCVarUpdateRecorder = PreyFunction<void(CCVarUpdateRecorder* const _this)>(0xE999B0);
	static inline auto FOnBeforeVarChange = PreyFunction<bool(CCVarUpdateRecorder* const _this, ICVar* pVar, const char* sNewValue)>(0x1B933B0);
	static inline auto FOnAfterVarChange = PreyFunction<void(CCVarUpdateRecorder* const _this, ICVar* pVar)>(0xEA2390);
	static inline auto FReset = PreyFunction<void(CCVarUpdateRecorder* const _this)>(0xEA2670);
	static inline auto FGetCVars = PreyFunction<const std::vector<CCVarUpdateRecorder::SUpdateRecord>& (const CCVarUpdateRecorder* const _this)>(0xE9AD30);
	static inline auto FGetCVar = PreyFunction<const CCVarUpdateRecorder::SUpdateRecord* (const CCVarUpdateRecorder* const _this, const char* cvarName)>(0xE9ACC0);
};
#else // MOONCRASH
// Header file automatically created from a PDB.
#pragma once
#include <Prey/CrySystem/IConsole.h>

struct ICVar;
struct IConsole;
struct IConsoleCmdArgs;

// CCVarUpdateRecorder
// Header:  CryEngine/renderdll/common/RendererCVars.h
// Include: Prey/RenderDll/Common/RendererCVars.h
class CCVarUpdateRecorder : public IConsoleVarSink
{ // Size=64 (0x40)
public:
	// CCVarUpdateRecorder::SUpdateRecord
	// Header:  CryEngine/renderdll/common/RendererCVars.h
	struct SUpdateRecord
	{ // Size=80 (0x50)
		union
		{
			int intValue;
			float floatValue;
			char stringValue[64];
		};

		const char* name;
		int type;

	#if 0
		SUpdateRecord(ICVar* _arg0_);
	#endif
	};

	using CVarList = std::vector<CCVarUpdateRecorder::SUpdateRecord>;

	std::vector<CCVarUpdateRecorder::SUpdateRecord> m_updatedCVars[2];
	IConsole* m_pConsole;

	CCVarUpdateRecorder(IConsole* pConsole);
	virtual ~CCVarUpdateRecorder();
	virtual bool OnBeforeVarChange(ICVar* pVar, const char* sNewValue);
	virtual void OnAfterVarChange(ICVar* pVar);
	void Reset() { FReset(this); }
	const std::vector<CCVarUpdateRecorder::SUpdateRecord>& GetCVars() const { return FGetCVars(this); }
	const CCVarUpdateRecorder::SUpdateRecord* GetCVar(const char* cvarName) const { return FGetCVar(this, cvarName); }

	static inline auto FCCVarUpdateRecorderOv1 = PreyFunction<void(CCVarUpdateRecorder* const _this, IConsole* pConsole)>(0xEB5E60);
	static inline auto FBitNotCCVarUpdateRecorder = PreyFunction<void(CCVarUpdateRecorder* const _this)>(0xEB5EB0);
	static inline auto FOnBeforeVarChange = PreyFunction<bool(CCVarUpdateRecorder* const _this, ICVar* pVar, const char* sNewValue)>(0x1A302A0);
	static inline auto FOnAfterVarChange = PreyFunction<void(CCVarUpdateRecorder* const _this, ICVar* pVar)>(0xEBE870);
	static inline auto FReset = PreyFunction<void(CCVarUpdateRecorder* const _this)>(0xEBEB50);
	static inline auto FGetCVars = PreyFunction<const std::vector<CCVarUpdateRecorder::SUpdateRecord>& (const CCVarUpdateRecorder* const _this)>(0xEB7230);
	static inline auto FGetCVar = PreyFunction<const CCVarUpdateRecorder::SUpdateRecord* (const CCVarUpdateRecorder* const _this, const char* cvarName)>(0xEB71C0);
};

// CRendererCVars
// Header:  CryEngine/renderdll/common/RendererCVars.h
// Include: Prey/RenderDll/Common/RendererCVars.h
class CRendererCVars
{ // Size=88 (0x58)
public:
	static inline auto CV_r_ShowDynTexturesFilter = PreyGlobal<ICVar*>(0x2C7DBC8);
	static inline auto CV_r_ShaderCompilerServer = PreyGlobal<ICVar*>(0x2C7DBD0);
	static inline auto CV_r_ShaderCompilerFolderName = PreyGlobal<ICVar*>(0x2C7DBD8);
	static inline auto CV_r_ShaderCompilerFolderSuffix = PreyGlobal<ICVar*>(0x2C7DBE0);
	static inline auto CV_r_ShaderEmailTags = PreyGlobal<ICVar*>(0x2C7DBE8);
	static inline auto CV_r_ShaderEmailCCs = PreyGlobal<ICVar*>(0x2C7DBF0);
	static inline auto CV_r_excludeshader = PreyGlobal<ICVar*>(0x2C7DBF8);
	static inline auto CV_r_excludemesh = PreyGlobal<ICVar*>(0x2C7DC00);
	static inline auto CV_r_ShowTexture = PreyGlobal<ICVar*>(0x2C7DC08);
	static inline auto CV_r_TexturesStreamingDebugfilter = PreyGlobal<ICVar*>(0x2C7DC10);
	static inline auto CV_r_vsync = PreyGlobal<int>(0x2C7DC18);
	static inline auto CV_r_overrideRefreshRate = PreyGlobal<float>(0x2C7DC1C);
	static inline auto CV_r_overrideScanlineOrder = PreyGlobal<int>(0x2C7DC20);
	static inline auto CV_r_overrideDXGIOutput = PreyGlobal<int>(0x2C7DC24);
	static inline auto CV_r_FullscreenPreemption = PreyGlobal<int>(0x23D8CD0);
	static inline auto CV_r_SyncToFrameFence = PreyGlobal<int>(0x2C7DC28);
	static inline auto CV_r_GraphicsPipeline = PreyGlobal<int>(0x2C7DC2C);
	static inline auto CV_r_DeferredShadingTiled = PreyGlobal<int>(0x2C7DC30);
	static inline auto CV_r_DeferredShadingTiledDebug = PreyGlobal<int>(0x2C7DC34);
	static inline auto CV_r_DeferredShadingTiledHairQuality = PreyGlobal<int>(0x2C7DC38);
	static inline auto CV_r_DeferredShadingSSS = PreyGlobal<int>(0x2C7DC3C);
	static inline auto CV_r_MotionVectors = PreyGlobal<int>(0x2C7DC40);
	static inline auto CV_r_MotionBlur = PreyGlobal<int>(0x2C7DC44);
	static inline auto CV_r_MotionBlurQuality = PreyGlobal<int>(0x2C7DC48);
	static inline auto CV_r_MotionBlurGBufferVelocity = PreyGlobal<int>(0x2C7DC4C);
	static inline auto CV_r_MotionBlurThreshold = PreyGlobal<float>(0x2C7DC50);
	static inline auto CV_r_minimizeLatency = PreyGlobal<int>(0x2C7DC54);
	static inline auto CV_r_DeferredShadingAmbientSClear = PreyGlobal<int>(0x2C7DC58);
	static inline auto CV_r_batchtype = PreyGlobal<int>(0x2C7DC5C);
	static inline auto CV_r_SilhouettePOM = PreyGlobal<int>(0x2C7DC60);
	static inline auto CV_r_WaterTessellationHW = PreyGlobal<int>(0x2C7DC64);
	static inline auto CV_r_tessellationdebug = PreyGlobal<int>(0x2C7DC68);
	static inline auto CV_r_tessellationtrianglesize = PreyGlobal<float>(0x2C7DC6C);
	static inline auto CV_r_displacementfactor = PreyGlobal<float>(0x2C7DC70);
	static inline auto CV_r_geominstancingthreshold = PreyGlobal<int>(0x2C7DC74);
	static inline auto CV_r_ShadowsDepthBoundNV = PreyGlobal<int>(0x2C7DC78);
	static inline auto CV_r_ShadowsPCFiltering = PreyGlobal<int>(0x2C7DC7C);
	static inline auto CV_r_rc_autoinvoke = PreyGlobal<int>(0x2C7DC80);
	static inline auto CV_r_Refraction = PreyGlobal<int>(0x2C7DC84);
	static inline auto CV_r_PostProcessReset = PreyGlobal<int>(0x2C7DC88);
	static inline auto CV_r_colorRangeCompression = PreyGlobal<int>(0x2C7DC8C);
	static inline auto CV_r_colorgrading_selectivecolor = PreyGlobal<int>(0x2C7DC90);
	static inline auto CV_r_colorgrading_charts = PreyGlobal<int>(0x2C7DC94);
	static inline auto CV_r_ColorgradingChartsCache = PreyGlobal<int>(0x2C7DC98);
	static inline auto CV_r_ShaderCompilerPort = PreyGlobal<int>(0x2C7DC9C);
	static inline auto CV_r_ShowDynTexturesMaxCount = PreyGlobal<int>(0x2C7DCA0);
	static inline auto CV_r_ShaderCompilerDontCache = PreyGlobal<int>(0x2C7DCA4);
	static inline auto CV_r_dyntexmaxsize = PreyGlobal<int>(0x2C7DCA8);
	static inline auto CV_r_texmaxanisotropy = PreyGlobal<int>(0x2C7DCAC);
	static inline auto CV_r_texturesskiplowermips = PreyGlobal<int>(0x2C7DCB0);
	static inline auto CV_r_rendertargetpoolsize = PreyGlobal<int>(0x2C7DCB4);
	static inline auto CV_r_texturesstreamingsync = PreyGlobal<int>(0x2C7DCB8);
	static inline auto CV_r_watercausticsdeferred = PreyGlobal<int>(0x2C7DCBC);
	static inline auto CV_r_WaterUpdateThread = PreyGlobal<int>(0x2C7DCC0);
	static inline auto CV_r_watercaustics = PreyGlobal<int>(0x2C7DCC4);
	static inline auto CV_r_watervolumecaustics = PreyGlobal<int>(0x2C7DCC8);
	static inline auto CV_r_watervolumecausticsdensity = PreyGlobal<int>(0x2C7DCCC);
	static inline auto CV_r_watervolumecausticsresolution = PreyGlobal<int>(0x2C7DCD0);
	static inline auto CV_r_shaderspreactivate = PreyGlobal<int>(0x2C7DCD4);
	static inline auto CV_r_shadersremotecompiler = PreyGlobal<int>(0x2C7DCD8);
	static inline auto CV_r_shadersasynccompiling = PreyGlobal<int>(0x2C7DCDC);
	static inline auto CV_r_shadersasyncactivation = PreyGlobal<int>(0x2C7DCE0);
	static inline auto CV_r_shadersasyncmaxthreads = PreyGlobal<int>(0x2C7DCE4);
	static inline auto CV_r_shaderscachedeterministic = PreyGlobal<int>(0x2C7DCE8);
	static inline auto CV_r_shaderssubmitrequestline = PreyGlobal<int>(0x2C7DCEC);
	static inline auto CV_r_shaderslogcachemisses = PreyGlobal<int>(0x2C7DCF0);
	static inline auto CV_r_meshpoolsize = PreyGlobal<int>(0x2C7DCF4);
	static inline auto CV_r_meshinstancepoolsize = PreyGlobal<int>(0x2C7DCF8);
	static inline auto CV_r_multigpu = PreyGlobal<int>(0x2C7DCFC);
	static inline auto CV_r_beams = PreyGlobal<int>(0x2C7DD00);
	static inline auto CV_r_nodrawnear = PreyGlobal<int>(0x2C7DD04);
	static inline auto CV_r_DrawNearShadows = PreyGlobal<int>(0x2C7DD08);
	static inline auto CV_r_scissor = PreyGlobal<int>(0x2C7DD0C);
	static inline auto CV_r_usezpass = PreyGlobal<int>(0x2C7DD10);
	static inline auto CV_r_ShowVideoMemoryStats = PreyGlobal<int>(0x2C7DD14);
	static inline auto CV_r_TexturesStreamingDebugMinSize = PreyGlobal<int>(0x2C7DD18);
	static inline auto CV_r_TexturesStreamingDebugMinMip = PreyGlobal<int>(0x2C7DD1C);
	static inline auto CV_r_enableAltTab = PreyGlobal<int>(0x2C7DD20);
	static inline auto CV_r_DynTexSourceSharedRTWidth = PreyGlobal<int>(0x2C7DD24);
	static inline auto CV_r_DynTexSourceSharedRTHeight = PreyGlobal<int>(0x2C7DD28);
	static inline auto CV_r_DynTexSourceUseSharedRT = PreyGlobal<int>(0x2C7DD2C);
	static inline auto CV_r_ScreenShotFileName = PreyGlobal<ICVar*>(0x2C7DD30);
	static inline auto CV_r_GetScreenShot = PreyGlobal<int>(0x2C7DD38);
	static inline auto CV_r_BreakOnError = PreyGlobal<int>(0x2C7DD3C);
	static inline auto CV_r_TexturesStreamPoolSize = PreyGlobal<int>(0x2C7DD40);
	static inline auto CV_r_TexturesStreamPoolSecondarySize = PreyGlobal<int>(0x2C7DD44);
	static inline auto CV_r_ReprojectOnlyStaticObjects = PreyGlobal<int>(0x2C7DD48);
	static inline auto CV_r_ReadZBufferDirectlyFromVMEM = PreyGlobal<int>(0x2C7DD4C);
	static inline auto CV_r_durango_async_dips = PreyGlobal<int>(0x2C7DD50);
	static inline auto CV_r_durango_async_dips_sync = PreyGlobal<int>(0x2C7DD54);
	static inline auto CV_r_D3D12SubmissionThread = PreyGlobal<int>(0x2C7DD58);
	static inline auto CV_r_D3D12WaitableSwapChain = PreyGlobal<int>(0x2C7DD5C);
	static inline auto CV_r_D3D12BatchResourceBarriers = PreyGlobal<int>(0x2C7DD60);
	static inline auto CV_r_D3D12EarlyResourceBarriers = PreyGlobal<int>(0x2C7DD64);
	static inline auto CV_r_D3D12AsynchronousCompute = PreyGlobal<int>(0x2C7DD68);
	static inline auto CV_r_D3D12HardwareComputeQueue = PreyGlobal<int>(0x2C7DD6C);
	static inline auto CV_r_D3D12HardwareCopyQueue = PreyGlobal<int>(0x2C7DD70);
	static inline auto CV_r_ReverseDepth = PreyGlobal<int>(0x2C7DD74);
	static inline auto CV_r_EnableDebugLayer = PreyGlobal<int>(0x2C7DD78);
	static inline auto CV_r_NoDraw = PreyGlobal<int>(0x2C7DD7C);
	static inline auto CV_r_UpdateInstances = PreyGlobal<int>(0x2C7DD80);
	static inline auto CV_r_stats = PreyGlobal<int>(0x2C7DD84);
	static inline auto CV_r_statsMinDrawcalls = PreyGlobal<int>(0x2C7DD88);
	static inline auto CV_r_profiler = PreyGlobal<int>(0x2C7DD8C);
	static inline auto CV_r_profilerTargetFPS = PreyGlobal<float>(0x2C7DD90);
	static inline auto CV_r_LightPropagationVolumes = PreyGlobal<int>(0x2C7DD94);
	static inline auto CV_r_ShadowPoolMaxFrames = PreyGlobal<int>(0x2C7DD98);
	static inline auto CV_r_predicatedtiling = PreyGlobal<int>(0x2C7DD9C);
	static inline auto CV_r_useESRAM = PreyGlobal<int>(0x2C7DDA0);
	static inline auto CV_r_multithreaded = PreyGlobal<int>(0x2C7DDA4);
	static inline auto CV_r_multithreadedDrawing = PreyGlobal<int>(0x2C7DDA8);
	static inline auto CV_r_multithreadedDrawingCoalesceMode = PreyGlobal<int>(0x2C7DDAC);
	static inline auto CV_r_multithreadedDrawingMinNonJobs = PreyGlobal<int>(0x2C7DDB0);
	static inline auto CV_r_multithreadedDrawingMinJobSize = PreyGlobal<int>(0x2C7DDB4);
	static inline auto CV_r_deferredshadingLightVolumes = PreyGlobal<int>(0x2C7DDB8);
	static inline auto CV_r_deferredDecals = PreyGlobal<int>(0x2C7DDBC);
	static inline auto CV_r_deferredDecalsDebug = PreyGlobal<int>(0x2C7DDC0);
	static inline auto CV_r_DeferredShadingScissor = PreyGlobal<int>(0x2C7DDC4);
	static inline auto CV_r_DeferredShadingDebug = PreyGlobal<int>(0x2C7DDC8);
	static inline auto CV_r_DeferredShadingDebugGBuffer = PreyGlobal<int>(0x2C7DDCC);
	static inline auto CV_r_DeferredShadingEnvProbes = PreyGlobal<int>(0x2C7DDD0);
	static inline auto CV_r_DeferredShadingAmbient = PreyGlobal<int>(0x2C7DDD4);
	static inline auto CV_r_DeferredShadingAmbientLights = PreyGlobal<int>(0x2C7DDD8);
	static inline auto CV_r_DeferredShadingLights = PreyGlobal<int>(0x2C7DDDC);
	static inline auto CV_r_DeferredShadingAreaLights = PreyGlobal<int>(0x2C7DDE0);
	static inline auto CV_r_DeferredShadingTiledLightsPriority = PreyGlobal<int>(0x2C7DDE4);
	static inline auto CV_r_DeferredShadingGameplayLightBias = PreyGlobal<float>(0x2C7DDE8);
	static inline auto CV_r_DeferredShadingStencilPrepass = PreyGlobal<int>(0x2C7DDEC);
	static inline auto CV_r_PixelOutputMode = PreyGlobal<int>(0x2C7DDF0);
	static inline auto CV_r_HDRRendering = PreyGlobal<int>(0x2C7DDF4);
	static inline auto CV_r_HDRDebug = PreyGlobal<int>(0x2C7DDF8);
	static inline auto CV_r_HDRBloom = PreyGlobal<int>(0x2C7DDFC);
	static inline auto CV_r_HDRBloomQuality = PreyGlobal<int>(0x2C7DE00);
	static inline auto CV_r_HDRVignetting = PreyGlobal<int>(0x2C7DE04);
	static inline auto CV_r_HDRTexFormat = PreyGlobal<int>(0x2C7DE08);
	static inline auto CV_r_HDRRangeAdapt = PreyGlobal<int>(0x2C7DE0C);
	static inline auto CV_r_HDREyeAdaptationMode = PreyGlobal<int>(0x2C7DE10);
	static inline auto CV_r_geominstancing = PreyGlobal<int>(0x2C7DE14);
	static inline auto CV_r_geominstancingdebug = PreyGlobal<int>(0x2C7DE18);
	static inline auto CV_r_materialsbatching = PreyGlobal<int>(0x2C7DE1C);
	static inline auto CV_r_UseShadowsPool = PreyGlobal<int>(0x2C7DE20);
	static inline auto CV_r_shadowtexformat = PreyGlobal<int>(0x2C7DE24);
	static inline auto CV_r_ShadowsMaskResolution = PreyGlobal<int>(0x2C7DE28);
	static inline auto CV_r_ShadowsMaskDownScale = PreyGlobal<int>(0x2C7DE2C);
	static inline auto CV_r_CBufferUseNativeDepth = PreyGlobal<int>(0x2C7DE30);
	static inline auto CV_r_ShadowsStencilPrePass = PreyGlobal<int>(0x2C7DE34);
	static inline auto CV_r_ShadowMaskStencilPrepass = PreyGlobal<int>(0x2C7DE38);
	static inline auto CV_r_ShadowsGridAligned = PreyGlobal<int>(0x2C7DE3C);
	static inline auto CV_r_ShadowPass = PreyGlobal<int>(0x2C7DE40);
	static inline auto CV_r_ShadowGen = PreyGlobal<int>(0x2C7DE44);
	static inline auto CV_r_ShadowGenDepthClip = PreyGlobal<int>(0x2C7DE48);
	static inline auto CV_r_ShadowsUseClipVolume = PreyGlobal<int>(0x2C7DE4C);
	static inline auto CV_r_shadowblur = PreyGlobal<int>(0x2C7DE50);
	static inline auto CV_r_ShadowGenMode = PreyGlobal<int>(0x2C7DE54);
	static inline auto CV_r_ShadowsCache = PreyGlobal<int>(0x2C7DE58);
	static inline auto CV_r_ShadowsCacheFormat = PreyGlobal<int>(0x2C7DE5C);
	static inline auto CV_r_ShadowsNearestMapResolution = PreyGlobal<int>(0x2C7DE60);
	static inline auto CV_r_ShadowsScreenSpace = PreyGlobal<int>(0x2C7DE64);
	static inline auto CV_r_deferredshadingDBTstencil = PreyGlobal<int>(0x2C7DE68);
	static inline auto CV_r_sunshafts = PreyGlobal<int>(0x2C7DE6C);
	static inline auto CV_r_MergeShadowDrawcalls = PreyGlobal<int>(0x2C7DE70);
	static inline auto CV_r_PostProcess_CB = PreyGlobal<int>(0x2C7DE74);
	static inline auto CV_r_PostProcess = PreyGlobal<int>(0x2C7DE78);
	static inline auto CV_r_PostProcessFilters = PreyGlobal<int>(0x2C7DE7C);
	static inline auto CV_r_PostProcessGameFx = PreyGlobal<int>(0x2C7DE80);
	static inline auto CV_r_PostProcessParamsBlending = PreyGlobal<int>(0x2C7DE84);
	static inline auto CV_r_colorgrading = PreyGlobal<int>(0x2C7DE88);
	static inline auto CV_r_colorgrading_levels = PreyGlobal<int>(0x2C7DE8C);
	static inline auto CV_r_colorgrading_filters = PreyGlobal<int>(0x2C7DE90);
	static inline auto CV_r_showdyntextures = PreyGlobal<int>(0x2C7DE94);
	static inline auto CV_r_shownormals = PreyGlobal<int>(0x2C7DE98);
	static inline auto CV_r_showlines = PreyGlobal<int>(0x2C7DE9C);
	static inline auto CV_r_showtangents = PreyGlobal<int>(0x2C7DEA0);
	static inline auto CV_r_showtimegraph = PreyGlobal<int>(0x2C7DEA4);
	static inline auto CV_r_DebugFontRendering = PreyGlobal<int>(0x2C7DEA8);
	static inline auto CV_profileStreaming = PreyGlobal<int>(0x2C7DEAC);
	static inline auto CV_r_graphstyle = PreyGlobal<int>(0x2C7DEB0);
	static inline auto CV_r_showbufferusage = PreyGlobal<int>(0x2C7DEB4);
	static inline auto CV_r_ProfileShadersSmooth = PreyGlobal<int>(0x2C7DEB8);
	static inline auto CV_r_ProfileShadersGroupByName = PreyGlobal<int>(0x2C7DEBC);
	static inline auto CV_r_texpostponeloading = PreyGlobal<int>(0x2C7DEC0);
	static inline auto CV_r_texlog = PreyGlobal<int>(0x2C7DEC4);
	static inline auto CV_r_texnoload = PreyGlobal<int>(0x2C7DEC8);
	static inline auto CV_r_texturecompiling = PreyGlobal<int>(0x2C7DECC);
	static inline auto CV_r_texturecompilingIndicator = PreyGlobal<int>(0x2C7DED0);
	static inline auto CV_r_texturesstreaming = PreyGlobal<int>(0x2C7DED4);
	static inline auto CV_r_TexturesStreamingDebug = PreyGlobal<int>(0x2C7DED8);
	static inline auto CV_r_texturesstreamingnoupload = PreyGlobal<int>(0x2C7DEDC);
	static inline auto CV_r_texturesstreamingonlyvideo = PreyGlobal<int>(0x2C7DEE0);
	static inline auto CV_r_texturesstreamingmipfading = PreyGlobal<int>(0x2C7DEE4);
	static inline auto CV_r_texturesstreamingUpdateType = PreyGlobal<int>(0x2C7DEE8);
	static inline auto CV_r_texturesstreamingPrecacheRounds = PreyGlobal<int>(0x2C7DEEC);
	static inline auto CV_r_texturesstreamingSuppress = PreyGlobal<int>(0x2C7DEF0);
	static inline auto CV_r_texturesstreamingSkipMips = PreyGlobal<int>(0x2C7DEF4);
	static inline auto CV_r_texturesstreamingMinUsableMips = PreyGlobal<int>(0x2C7DEF8);
	static inline auto CV_r_texturesstreamingJobUpdate = PreyGlobal<int>(0x2C7DEFC);
	static inline auto CV_r_texturesstreamingDeferred = PreyGlobal<int>(0x2C7DF00);
	static inline auto CV_r_texturesstreamingPostponeMips = PreyGlobal<int>(0x2C7DF04);
	static inline auto CV_r_texturesstreamingPostponeThresholdMip = PreyGlobal<int>(0x2C7DF08);
	static inline auto CV_r_texturesstreamingMinReadSizeKB = PreyGlobal<int>(0x2C7DF0C);
	static inline auto CV_r_envtexresolution = PreyGlobal<int>(0x2C7DF10);
	static inline auto CV_r_waterreflections_mgpu = PreyGlobal<int>(0x2C7DF14);
	static inline auto CV_r_waterreflections_use_min_offset = PreyGlobal<int>(0x2C7DF18);
	static inline auto CV_r_waterreflections = PreyGlobal<int>(0x2C7DF1C);
	static inline auto CV_r_waterreflections_quality = PreyGlobal<int>(0x2C7DF20);
	static inline auto CV_r_water_godrays = PreyGlobal<int>(0x2C7DF24);
	static inline auto CV_r_reflections = PreyGlobal<int>(0x2C7DF28);
	static inline auto CV_r_reflections_quality = PreyGlobal<int>(0x2C7DF2C);
	static inline auto CV_r_dof = PreyGlobal<int>(0x2C7DF30);
	static inline auto CV_r_texNoAnisoAlphaTest = PreyGlobal<int>(0x2C7DF34);
	static inline auto CV_r_reloadshaders = PreyGlobal<int>(0x2C7DF38);
	static inline auto CV_r_detailtextures = PreyGlobal<int>(0x2C7DF3C);
	static inline auto CV_r_texbindmode = PreyGlobal<int>(0x2C7DF40);
	static inline auto CV_r_nodrawshaders = PreyGlobal<int>(0x2C7DF44);
	static inline auto CV_r_shadersdebug = PreyGlobal<int>(0x2C7DF48);
	static inline auto CV_r_shadersignoreincludeschanging = PreyGlobal<int>(0x2C7DF4C);
	static inline auto CV_r_shaderslazyunload = PreyGlobal<int>(0x2C7DF50);
	static inline auto CV_r_shadersAllowCompilation = PreyGlobal<int>(0x2C7DF54);
	static inline auto CV_r_shaderscompileautoactivate = PreyGlobal<int>(0x2C7DF58);
	static inline auto CV_r_shadersediting = PreyGlobal<int>(0x2C7DF5C);
	static inline auto CV_r_ReflectTextureSlots = PreyGlobal<int>(0x2C7DF60);
	static inline auto CV_r_debugrendermode = PreyGlobal<int>(0x2C7DF64);
	static inline auto CV_r_debugrefraction = PreyGlobal<int>(0x2C7DF68);
	static inline auto CV_r_meshprecache = PreyGlobal<int>(0x2C7DF6C);
	static inline auto CV_r_validateDraw = PreyGlobal<int>(0x2C7DF70);
	static inline auto CV_r_flares = PreyGlobal<int>(0x23D8CD4);
	static inline auto CV_r_flareHqShafts = PreyGlobal<int>(0x2C7DF74);
	static inline auto CV_r_ZPassDepthSorting = PreyGlobal<int>(0x2C7DF78);
	static inline auto CV_r_TransparentPasses = PreyGlobal<int>(0x2C7DF7C);
	static inline auto CV_r_SkipAlphaTested = PreyGlobal<int>(0x2C7DF80);
	static inline auto CV_r_TranspDepthFixup = PreyGlobal<int>(0x2C7DF84);
	static inline auto CV_r_usehwskinning = PreyGlobal<int>(0x2C7DF88);
	static inline auto CV_r_ParticlesSoftIsec = PreyGlobal<int>(0x2C7DF8C);
	static inline auto CV_r_ParticlesRefraction = PreyGlobal<int>(0x2C7DF90);
	static inline auto CV_r_ParticlesTessellation = PreyGlobal<int>(0x2C7DF94);
	static inline auto CV_r_ParticlesTessellationTriSize = PreyGlobal<int>(0x2C7DF98);
	static inline auto CV_r_ParticlesAmountGI = PreyGlobal<float>(0x2C7DF9C);
	static inline auto CV_r_ParticlesHalfRes = PreyGlobal<int>(0x2C7DFA0);
	static inline auto CV_r_ParticlesHalfResAmount = PreyGlobal<int>(0x2C7DFA4);
	static inline auto CV_r_ParticlesHalfResBlendMode = PreyGlobal<int>(0x2C7DFA8);
	static inline auto CV_r_ParticlesInstanceVertices = PreyGlobal<int>(0x2C7DFAC);
	static inline auto CV_r_AntialiasingModeEditor = PreyGlobal<int>(0x2C7DFB0);
	static inline auto CV_r_AntialiasingModeDebug = PreyGlobal<int>(0x2C7DFB4);
	static inline auto CV_r_rain = PreyGlobal<int>(0x2C7DFB8);
	static inline auto CV_r_rain_ignore_nearest = PreyGlobal<int>(0x2C7DFBC);
	static inline auto CV_r_snow = PreyGlobal<int>(0x2C7DFC0);
	static inline auto CV_r_snow_halfres = PreyGlobal<int>(0x2C7DFC4);
	static inline auto CV_r_snow_displacement = PreyGlobal<int>(0x2C7DFC8);
	static inline auto CV_r_snowFlakeClusters = PreyGlobal<int>(0x2C7DFCC);
	static inline auto CV_r_customvisions = PreyGlobal<int>(0x2C7DFD0);
	static inline auto CV_r_DofMode = PreyGlobal<int>(0x2C7DFD4);
	static inline auto CV_r_DofBokehQuality = PreyGlobal<int>(0x2C7DFD8);
	static inline auto CV_r_nohwgamma = PreyGlobal<int>(0x2C7DFDC);
	static inline auto CV_r_wireframe = PreyGlobal<int>(0x2C7DFE0);
	static inline auto CV_r_printmemoryleaks = PreyGlobal<int>(0x2C7DFE4);
	static inline auto CV_r_releaseallresourcesonexit = PreyGlobal<int>(0x2C7DFE8);
	static inline auto CV_r_character_nodeform = PreyGlobal<int>(0x2C7DFEC);
	static inline auto CV_r_ZPassOnly = PreyGlobal<int>(0x2C7DFF0);
	static inline auto CV_r_VegetationAlphaTestOnly = PreyGlobal<int>(0x2C7DFF4);
	static inline auto CV_r_measureoverdraw = PreyGlobal<int>(0x2C7DFF8);
	static inline auto CV_r_ShowLightBounds = PreyGlobal<int>(0x2C7DFFC);
	static inline auto CV_r_MergeRenderChunks = PreyGlobal<int>(0x2C7E000);
	static inline auto CV_r_TextureCompressor = PreyGlobal<int>(0x2C7E004);
	static inline auto CV_r_TexturesStreamingDebugDumpIntoLog = PreyGlobal<int>(0x2C7E008);
	static inline auto CV_e_DebugTexelDensity = PreyGlobal<int>(0x2C7E00C);
	static inline auto CV_r_RefractionPartialResolves = PreyGlobal<int>(0x2C7E010);
	static inline auto CV_r_RefractionPartialResolvesDebug = PreyGlobal<int>(0x2C7E014);
	static inline auto CV_r_Batching = PreyGlobal<int>(0x2C7E018);
	static inline auto CV_r_Unlit = PreyGlobal<int>(0x2C7E01C);
	static inline auto CV_r_HideSunInCubemaps = PreyGlobal<int>(0x2C7E020);
	static inline auto CV_r_ParticlesDebug = PreyGlobal<int>(0x2C7E024);
	static inline auto CV_e_DebugRenderMode = PreyGlobal<int>(0x2C7E028);
	static inline auto CV_r_DebugAmbientEnable = PreyGlobal<int>(0x2C7E02C);
	static inline auto CV_r_ArkLateNearTransparency = PreyGlobal<int>(0x2C7E030);
	static inline auto CV_r_ArkStarsMoveWithSun = PreyGlobal<int>(0x2C7E034);
	static inline auto CV_r_ArkStarOffsetPitch = PreyGlobal<float>(0x2C7E038);
	static inline auto CV_r_ArkStarOffsetRoll = PreyGlobal<float>(0x2C7E03C);
	static inline auto CV_r_ArkStarOffsetYaw = PreyGlobal<float>(0x2C7E040);
	static inline auto CV_r_ZPrepassMaxDist = PreyGlobal<float>(0x2C7E044);
	static inline auto CV_r_FlaresChromaShift = PreyGlobal<float>(0x2C7E048);
	static inline auto CV_r_FlaresIrisShaftMaxPolyNum = PreyGlobal<int>(0x2C7E04C);
	static inline auto CV_r_FlaresTessellationRatio = PreyGlobal<float>(0x2C7E050);
	static inline auto CV_r_drawnearfov = PreyGlobal<float>(0x2C7E054);
	static inline auto CV_r_measureoverdrawscale = PreyGlobal<float>(0x2C7E058);
	static inline auto CV_r_DeferredShadingLightLodRatio = PreyGlobal<float>(0x2C7E05C);
	static inline auto CV_r_DeferredShadingLightStencilRatio = PreyGlobal<float>(0x2C7E060);
	static inline auto CV_r_rainDistMultiplier = PreyGlobal<float>(0x2C7E064);
	static inline auto CV_r_rainOccluderSizeTreshold = PreyGlobal<float>(0x2C7E068);
	static inline auto CV_r_HDRRangeAdaptMaxRange = PreyGlobal<float>(0x2C7E06C);
	static inline auto CV_r_HDRRangeAdaptMax = PreyGlobal<float>(0x2C7E070);
	static inline auto CV_r_HDRRangeAdaptLBufferMaxRange = PreyGlobal<float>(0x2C7E074);
	static inline auto CV_r_HDRRangeAdaptLBufferMax = PreyGlobal<float>(0x2C7E078);
	static inline auto CV_r_HDRRangeAdaptationSpeed = PreyGlobal<float>(0x2C7E07C);
	static inline auto CV_r_HDREyeAdaptationSpeed = PreyGlobal<float>(0x2C7E080);
	static inline auto CV_r_HDRGrainAmount = PreyGlobal<float>(0x2C7E084);
	static inline auto CV_r_Sharpening = PreyGlobal<float>(0x2C7E088);
	static inline auto CV_r_ChromaticAberration = PreyGlobal<float>(0x2C7E08C);
	static inline auto CV_r_dofMinZ = PreyGlobal<float>(0x2C7E090);
	static inline auto CV_r_dofMinZScale = PreyGlobal<float>(0x2C7E094);
	static inline auto CV_r_dofMinZBlendMult = PreyGlobal<float>(0x2C7E098);
	static inline auto CV_r_dofDilation = PreyGlobal<float>(0x2C7E09C);
	static inline auto CV_r_ShadowsBias = PreyGlobal<float>(0x2C7E0A0);
	static inline auto CV_r_shadowbluriness = PreyGlobal<float>(0x2C7E0A4);
	static inline auto CV_r_ShadowsAdaptionRangeClamp = PreyGlobal<float>(0x2C7E0A8);
	static inline auto CV_r_ShadowsAdaptionSize = PreyGlobal<float>(0x2C7E0AC);
	static inline auto CV_r_ShadowsAdaptionMin = PreyGlobal<float>(0x2C7E0B0);
	static inline auto CV_r_ShadowsParticleKernelSize = PreyGlobal<float>(0x2C7E0B4);
	static inline auto CV_r_ShadowsParticleJitterAmount = PreyGlobal<float>(0x2C7E0B8);
	static inline auto CV_r_ShadowsParticleAnimJitterAmount = PreyGlobal<float>(0x2C7E0BC);
	static inline auto CV_r_ShadowsParticleNormalEffect = PreyGlobal<float>(0x2C7E0C0);
	static inline auto CV_r_shadow_jittering = PreyGlobal<float>(0x2C7E0C4);
	static inline auto CV_r_ShadowPoolMaxTimeslicedUpdatesPerFrame = PreyGlobal<int>(0x2C7E0C8);
	static inline auto CV_r_ShadowCastingLightsMaxCount = PreyGlobal<int>(0x2C7E0CC);
	static inline auto CV_r_RenderMeshHashGridUnitSize = PreyGlobal<float>(0x2C7E0D0);
	static inline auto CV_r_PostprocessParamsBlendingTimeScale = PreyGlobal<float>(0x2C7E0D4);
	static inline auto CV_r_normalslength = PreyGlobal<float>(0x2C7E0D8);
	static inline auto CV_r_TexelsPerMeter = PreyGlobal<float>(0x2C7E0DC);
	static inline auto CV_r_TexturesStreamingMaxRequestedMB = PreyGlobal<float>(0x2C7E0E0);
	static inline auto CV_r_TexturesStreamingMaxRequestedJobs = PreyGlobal<int>(0x2C7E0E4);
	static inline auto CV_r_TexturesStreamingMipBias = PreyGlobal<float>(0x2C7E0E8);
	static inline auto CV_r_envtexupdateinterval = PreyGlobal<float>(0x2C7E0EC);
	static inline auto CV_r_TextureLodDistanceRatio = PreyGlobal<float>(0x2C7E0F0);
	static inline auto CV_r_water_godrays_distortion = PreyGlobal<float>(0x2C7E0F4);
	static inline auto CV_r_waterupdateFactor = PreyGlobal<float>(0x2C7E0F8);
	static inline auto CV_r_waterupdateDistance = PreyGlobal<float>(0x2C7E0FC);
	static inline auto CV_r_waterreflections_min_visible_pixels_update = PreyGlobal<float>(0x2C7E100);
	static inline auto CV_r_waterreflections_minvis_updatefactormul = PreyGlobal<float>(0x2C7E104);
	static inline auto CV_r_waterreflections_minvis_updatedistancemul = PreyGlobal<float>(0x2C7E108);
	static inline auto CV_r_waterreflections_offset = PreyGlobal<float>(0x2C7E10C);
	static inline auto CV_r_watercausticsdistance = PreyGlobal<float>(0x2C7E110);
	static inline auto CV_r_watervolumecausticssnapfactor = PreyGlobal<float>(0x2C7E114);
	static inline auto CV_r_watervolumecausticsmaxdistance = PreyGlobal<float>(0x2C7E118);
	static inline auto CV_r_detaildistance = PreyGlobal<float>(0x2C7E11C);
	static inline auto CV_r_DrawNearZRange = PreyGlobal<float>(0x2C7E120);
	static inline auto CV_r_DrawNearFarPlane = PreyGlobal<float>(0x2C7E124);
	static inline auto CV_r_rainamount = PreyGlobal<float>(0x2C7E128);
	static inline auto CV_r_MotionBlurShutterSpeed = PreyGlobal<float>(0x2C7E12C);
	static inline auto CV_r_MotionBlurCameraMotionScale = PreyGlobal<float>(0x2C7E130);
	static inline auto CV_r_MotionBlurMaxViewDist = PreyGlobal<float>(0x2C7E134);
	static inline auto CV_r_gamma = PreyGlobal<float>(0x2C7E138);
	static inline auto CV_r_contrast = PreyGlobal<float>(0x2C7E13C);
	static inline auto CV_r_brightness = PreyGlobal<float>(0x2C7E140);
	static inline auto CV_r_brightnessOffset = PreyGlobal<float>(0x2C7E144);
	static inline auto CV_r_ZFightingDepthScale = PreyGlobal<float>(0x2C7E148);
	static inline auto CV_r_ZFightingExtrude = PreyGlobal<float>(0x2C7E14C);
	static inline auto CV_r_FlashMatTexResQuality = PreyGlobal<float>(0x2C7E150);
	static inline auto CV_r_AntialiasingMode_CB = PreyGlobal<int>(0x2C7E154);
	static inline auto CV_r_AntialiasingMode = PreyGlobal<int>(0x2C7E158);
	static inline auto CV_r_AntialiasingModeSCull = PreyGlobal<int>(0x2C7E15C);
	static inline auto CV_r_AntialiasingTAAPattern = PreyGlobal<int>(0x2C7E160);
	static inline auto CV_r_AntialiasingTAAFalloffHiFreq = PreyGlobal<float>(0x2C7E164);
	static inline auto CV_r_AntialiasingTAAFalloffLowFreq = PreyGlobal<float>(0x2C7E168);
	static inline auto CV_r_AntialiasingTAASharpening = PreyGlobal<float>(0x2C7E16C);
	static inline auto CV_r_AntialiasingTSAAMipBias = PreyGlobal<float>(0x2C7E170);
	static inline auto CV_r_AntialiasingTSAASubpixelDetection = PreyGlobal<float>(0x2C7E174);
	static inline auto CV_r_AntialiasingTSAASmoothness = PreyGlobal<float>(0x2C7E178);
	static inline auto CV_r_FogDepthTest = PreyGlobal<float>(0x2C7E17C);
	static inline auto CV_r_FogShadows = PreyGlobal<int>(0x2C7E180);
	static inline auto CV_r_FogShadowsMode = PreyGlobal<int>(0x2C7E184);
	static inline auto CV_r_FogShadowsWater = PreyGlobal<int>(0x2C7E188);
	static inline auto CV_r_rain_maxviewdist = PreyGlobal<float>(0x2C7E18C);
	static inline auto CV_r_rain_maxviewdist_deferred = PreyGlobal<float>(0x2C7E190);
	static inline auto CV_r_SSReflections = PreyGlobal<int>(0x2C7E194);
	static inline auto CV_r_SSReflHalfRes = PreyGlobal<int>(0x2C7E198);
	static inline auto CV_r_ArkSSR = PreyGlobal<int>(0x2C7E19C);
	static inline auto CV_r_ssdo = PreyGlobal<int>(0x2C7E1A0);
	static inline auto CV_r_ssdoHalfRes = PreyGlobal<int>(0x2C7E1A4);
	static inline auto CV_r_ssdoColorBleeding = PreyGlobal<int>(0x2C7E1A8);
	static inline auto CV_r_ssdoRadius = PreyGlobal<float>(0x2C7E1AC);
	static inline auto CV_r_ssdoRadiusMin = PreyGlobal<float>(0x2C7E1B0);
	static inline auto CV_r_ssdoRadiusMax = PreyGlobal<float>(0x2C7E1B4);
	static inline auto CV_r_ssdoAmountDirect = PreyGlobal<float>(0x2C7E1B8);
	static inline auto CV_r_ssdoAmountAmbient = PreyGlobal<float>(0x2C7E1BC);
	static inline auto CV_r_ssdoAmountReflection = PreyGlobal<float>(0x2C7E1C0);
	static inline auto CV_r_ArkSSDO = PreyGlobal<int>(0x2C7E1C4);
	static inline auto CV_r_CustomResMaxSize = PreyGlobal<int>(0x2C7E1C8);
	static inline auto CV_r_CustomResWidth = PreyGlobal<int>(0x2C7E1CC);
	static inline auto CV_r_CustomResHeight = PreyGlobal<int>(0x2C7E1D0);
	static inline auto CV_r_Supersampling = PreyGlobal<int>(0x2C7E1D4);
	static inline auto CV_r_SupersamplingFilter = PreyGlobal<int>(0x2C7E1D8);
	static inline auto CV_r_buffer_banksize = PreyGlobal<int>(0x2C7E1DC);
	static inline auto CV_r_constantbuffer_banksize = PreyGlobal<int>(0x2C7E1E0);
	static inline auto CV_r_constantbuffer_watermark = PreyGlobal<int>(0x2C7E1E4);
	static inline auto CV_r_transient_pool_size = PreyGlobal<int>(0x2C7E1E8);
	static inline auto CV_r_buffer_enable_lockless_updates = PreyGlobal<int>(0x2C7E1EC);
	static inline auto CV_r_enable_full_gpu_sync = PreyGlobal<int>(0x2C7E1F0);
	static inline auto CV_r_buffer_pool_max_allocs = PreyGlobal<int>(0x2C7E1F4);
	static inline auto CV_r_buffer_pool_defrag_static = PreyGlobal<int>(0x2C7E1F8);
	static inline auto CV_r_buffer_pool_defrag_static_shared = PreyGlobal<int>(0x2C7E1FC);
	static inline auto CV_r_buffer_pool_defrag_dynamic = PreyGlobal<int>(0x2C7E200);
	static inline auto CV_r_buffer_pool_defrag_max_moves = PreyGlobal<int>(0x2C7E204);
	static inline auto CV_r_ParticleVerticePoolSize = PreyGlobal<int>(0x2C7E208);
	static inline auto CV_r_GeomCacheInstanceThreshold = PreyGlobal<int>(0x2C7E20C);
	static inline auto CV_r_VisAreaClipLightsPerPixel = PreyGlobal<int>(0x2C7E210);
	static inline auto CV_r_VolumetricFog = PreyGlobal<int>(0x2C7E214);
	static inline auto CV_r_VolumetricFogPerFrame = PreyGlobal<int>(0x2C7E218);
	static inline auto CV_r_VolumetricFogTexScale = PreyGlobal<int>(0x2C7E21C);
	static inline auto CV_r_VolumetricFogTexDepth = PreyGlobal<int>(0x2C7E220);
	static inline auto CV_r_VolumetricFogReprojectionBlendFactor = PreyGlobal<float>(0x2C7E224);
	static inline auto CV_r_VolumetricFogSample = PreyGlobal<int>(0x2C7E228);
	static inline auto CV_r_VolumetricFogShadow = PreyGlobal<int>(0x2C7E22C);
	static inline auto CV_r_VolumetricFogDownscaledSunShadow = PreyGlobal<int>(0x2C7E230);
	static inline auto CV_r_VolumetricFogDownscaledSunShadowRatio = PreyGlobal<int>(0x2C7E234);
	static inline auto CV_r_VolumetricFogReprojectionMode = PreyGlobal<int>(0x2C7E238);
	static inline auto CV_r_VolumetricFogMinimumLightBulbSize = PreyGlobal<float>(0x2C7E23C);
	static inline auto CV_r_VolumetricFogSunLightCorrection = PreyGlobal<int>(0x2C7E240);
	static inline auto CV_r_MorphFade = PreyGlobal<float>(0x2C7E244);
	static inline auto CV_d3d11_CBUpdateStats = PreyGlobal<int>(0x2C7E248);
	static inline auto CV_d3d11_forcedFeatureLevel = PreyGlobal<ICVar*>(0x2C7E250);
	static inline auto CV_d3d11_preventDriverThreading = PreyGlobal<int>(0x2C7E24C);
	static inline auto CV_r_VolumetricClouds = PreyGlobal<int>(0x2C7E258);
	static inline auto CV_r_VolumetricCloudsRaymarchStepNum = PreyGlobal<int>(0x2C7E25C);
	static inline auto CV_r_VolumetricCloudsPipeline = PreyGlobal<int>(0x2C7E260);
	static inline auto CV_r_VolumetricCloudsStereoReprojection = PreyGlobal<int>(0x2C7E264);
	static inline auto CV_r_VolumetricCloudsTemporalReprojection = PreyGlobal<int>(0x2C7E268);
	static inline auto CV_r_VolumetricCloudsShadowResolution = PreyGlobal<int>(0x2C7E26C);
	static inline auto CV_r_GpuParticles = PreyGlobal<int>(0x2C7E270);
	static inline auto CV_r_GpuParticlesConstantRadiusBoundingBoxes = PreyGlobal<int>(0x2C7E274);
	ICVar* CV_capture_frames;
	ICVar* CV_capture_folder;
	ICVar* CV_capture_file_format;
	ICVar* CV_capture_frame_once;
	ICVar* CV_capture_file_name;
	ICVar* CV_capture_file_prefix;
	ICVar* m_CVWidth;
	ICVar* m_CVHeight;
	ICVar* m_CVFullScreen;
	ICVar* m_CVColorBits;
	ICVar* m_CVDisplayInfo;
	static inline auto s_overscanBorders = PreyGlobal<Vec2>(0x2C7E280);
	static inline auto CV_r_LightBeamDepthPass = PreyGlobal<int>(0x2C7E278);
	static inline auto CV_r_EnableRenderDoc = PreyGlobal<int>(0x2C7E27C);

	void InitCVars() { FInitCVars(this); }
	static void Cmd_ShowRenderTarget(IConsoleCmdArgs* pArgs) { FCmd_ShowRenderTarget(pArgs); }
	static void OnChange_CachedShadows(ICVar* pCVar) { FOnChange_CachedShadows(pCVar); }
	static void OnChange_GeomInstancingThreshold(ICVar* pVar) { FOnChange_GeomInstancingThreshold(pVar); }
	static void OnChange_ArkSSR(ICVar* _pVar) { FOnChange_ArkSSR(_pVar); }
	static void OnChange_ArkSSDO(ICVar* _pVar) { FOnChange_ArkSSDO(_pVar); }

#if 0
	static int GetTexturesStreamPoolSize();
	void InitExternalCVars();
	void CacheCaptureCVars();
#endif

	static inline auto FInitCVars = PreyFunction<void(CRendererCVars* const _this)>(0xEB7250);
	static inline auto FCmd_ShowRenderTarget = PreyFunction<void(IConsoleCmdArgs* pArgs)>(0xEB60D0);
	static inline auto FOnChange_CachedShadows = PreyFunction<void(ICVar* pCVar)>(0xEBEA40);
	static inline auto FOnChange_GeomInstancingThreshold = PreyFunction<void(ICVar* pVar)>(0xEBEA80);
	static inline auto FOnChange_ArkSSR = PreyFunction<void(ICVar* _pVar)>(0xEBE920);
	static inline auto FOnChange_ArkSSDO = PreyFunction<void(ICVar* _pVar)>(0xEBE8D0);
};

// STextureNameAutoComplete
// Header:  CryEngine/renderdll/common/RendererCVars.h
// Include: Prey/RenderDll/Common/RendererCVars.cpp
struct STextureNameAutoComplete : public IConsoleArgumentAutoComplete
{ // Size=8 (0x8)
	virtual int GetCount() const;
	virtual const char* GetValue(int nIndex) const;

	static inline auto FGetCount = PreyFunction<int(const STextureNameAutoComplete* const _this)>(0xEB5550);
	static inline auto FGetValue = PreyFunction<const char* (const STextureNameAutoComplete* const _this, int nIndex)>(0xEB5580);
};
#endif // !MOONCRASH
