name: build-and-test

on:
  push:
  pull_request:
  workflow_dispatch:
  
  # Run GitHub Actions monthly to make sure CI isn't broken
  schedule:
    - cron: '0 0 1 * *'

jobs:
  build:
    strategy:
      matrix:
        buildType: [DebugChair, Release]
    
    runs-on: windows-latest
    
    env:
      VCPKG_ROOT: '${{github.workspace}}/vcpkg'

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4.5.0
      with:
        python-version: 3.11

    - name: CI Test 1
      run: |
        python ./Scripts/ci_space_debug.py
    
    - name: Restore artifacts, or setup vcpkg for building artifacts
      uses: lukka/run-vcpkg@v10
      id: runvcpkg
      with:
        vcpkgJsonGlob: 'vcpkg.json'
        vcpkgDirectory: '${{env.VCPKG_ROOT}}'
        vcpkgGitCommitId: 'a7b6122f6b6504d16d96117336a0562693579933'
        runVcpkgInstall: true
        

    - name: CI Test 2
      run: |
        python ./Scripts/ci_space_debug.py

    - name: Run CMake+vcpkg+Ninja+CTest to generate/build/test.
      uses: lukka/run-cmake@v10
      id: runcmake
      with:
        configurePreset: 'ninja-vcpkg'
        buildPreset: 'ninja-vcpkg'
        buildPresetAdditionalArgs: "[`--config`, `${{matrix.buildType}}`]"
      env:
        VCPKG_FORCE_SYSTEM_BINARIES: 1

    - name: CI Test 3
      run: |
        python ./Scripts/ci_space_debug.py

    - name: Remove object files
      run: |
        cd _build/ninja-vcpkg
        del /s /q *.obj
        del /s /q *.pch
        del /s /q *.ilk
      shell: cmd

    - name: CI Test 3.5
      run: |
        python ./Scripts/ci_space_debug.py

    - name: Archive dist files
      id: createDist
      run: |
        python ./Scripts/make_package.py --repo-path=. --build-path=_build/ninja-vcpkg --build-config ${{matrix.buildType}} --output-dir-path=_temp --temp-path=_temp
    
    - name: Upload binaries archive
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{steps.createDist.outputs.artifact_name}}
        path: _temp/${{steps.createDist.outputs.artifact_name}}.zip

    - name: CI Test 4
      run: |
        python ./Scripts/ci_space_debug.py

    - name: Upload symbols archive
      uses: actions/upload-artifact@v3.1.2
      with:
        name: ${{steps.createDist.outputs.artifact_name_symbols}}
        path: _temp/${{steps.createDist.outputs.artifact_name_symbols}}.zip

    - name: CI Test 5
      run: |
        python ./Scripts/ci_space_debug.py
